/***********************************************************
* Kuvaus: Verotuksen esimerkkilaskelmien pohja             *
***********************************************************/

/* 1. Esimerkkilaskentaa ohjaavat makromuuttujat */

%MACRO Aloitus;

%LET TYYPPI = ESIM; 			* Parametrien hakutapa, aina ESIM;

/* Seuraavia vaiheita ei ajeta jos arvot annetaan tämän koodin ulkopuolelta (&EG = 1) */

%IF &EG NE 1 %THEN %DO;

%LET TULOSNIMI_VE = vero_esim_&SYSDATE._1 ; * Simuloidun tulostiedoston nimi ;
%LET VALITUT = _ALL_;	* Tulostaulukossa näytettävät muuttujat ;
%LET EROTIN = 2;		* Tulosteessa käytettävä desimaalierotin, 1 = piste tai 2 = pilkku;
%LET DESIMAALIT = 2;	* Tulosteessa käytettävä desimaalien määrä (0-9);
%LET EXCEL = 1;			* Viedäänkö tulostaulukko automaattisesti Exceliin (1 = Kyllä, 0 = Ei) ;

* Inflaatiokorjaus. Euro- tai markkamääräisten parametrien haun yhteydessä suoritettavassa
  deflatoinnissa käytettävän kertoimen voi syöttää itse INF-makromuuttujaan
  (HUOM! desimaalit erotettava pisteellä .). Esim. jos yksi lainsäädäntövuoden euro on
  peruvuoden rahassa 95 senttiä, syötä arvoksi 0.95.
  Simuloinnin tulokset ilmoitetaan aina perusvuoden rahassa.
  Jos puolestaan haluaa käyttää automaattista inflaatiokorjausta, on vaihtoehtoja kaksi:
  - Elinkustannusindeksiin (kuluttajahintaindeksi, ind51) perustuva inflaatiokorjaus: INF = KHI
  - Ansiotasoindeksiin (ansio64) perustuva inflaatiokorjaus: INF = ATI ;

%LET INF = 1.00; * Syötä lukuarvo, KHI tai ATI;
%LET AVUOSI = 2025; * Perusvuosi inflaatiokorjausta varten ;
%LET PINDEKSI_VUOSI = pindeksi_vuosi; * Käytettävä indeksien parametritaulukko ;

* Käytettävien tiedostojen nimet;

%LET LAKIMAK_TIED_VE = VEROlakimakrot;	* Lakimakrotiedoston nimi ;
%LET PVERO = pvero;
%LET PVERO_VARALL = pvero_varall; 

%END;

* Ajetaan lakimakrot ja tallennetaan ne;

%INCLUDE "&LEVY&KENO&HAKEM&KENO.MAKROT&KENO&LAKIMAK_TIED_VE..sas";

%MEND Aloitus;

%Aloitus;


/* 2. Datan generointia ohjaavat makromuuttujat */

%MACRO Generoi_Muuttujat;

/* Seuraavia vaiheita ei ajeta jos arvot annetaan tämän koodin ulkopuolelta (&EG = 1) */

%IF &EG NE 1 %THEN %DO;

/* 2.1 Fiktiivinen data */

* Lainsäädäntövuosi (1980-);
%LET MINIMI_VERO_VUOSI = 2025;
%LET MAKSIMI_VERO_VUOSI = 2025;

* Palkkatulo (e/v);
%LET MINIMI_VERO_PTULO = 50000;
%LET MAKSIMI_VERO_PTULO = 50000; 
%LET KYNNYS_VERO_PTULO = 5000;

* Merityötulo (e/v);
%LET MINIMI_VERO_MERITULO = 0;
%LET MAKSIMI_VERO_MERITULO = 0; 
%LET KYNNYS_VERO_MERITULO = 5000;

* Muu työtulo kuin palkkatulo (e/v);
%LET MINIMI_VERO_MTULO = 0;
%LET MAKSIMI_VERO_MTULO = 0; 
%LET KYNNYS_VERO_MTULO = 200;

* Päivärahatulo (e/v);
%LET MINIMI_VERO_PRAHATULO = 0;
%LET MAKSIMI_VERO_PRAHATULO = 0;
%LET KYNNYS_VERO_PRAHATULO = 500;

* Eläketulo (e/v);
%LET MINIMI_VERO_ETULO = 0;
%LET MAKSIMI_VERO_ETULO = 0;
%LET KYNNYS_VERO_ETULO = 500;

* Opintoraha (e/v);
%LET MINIMI_VERO_OPRAHA = 0;
%LET MAKSIMI_VERO_OPRAHA = 0;
%LET KYNNYS_VERO_OPRAHA = 100;

* Osinkotulo ansiotulona (e/v);
%LET MINIMI_VERO_OSANSTULO = 0;
%LET MAKSIMI_VERO_OSANSTULO = 0;  
%LET KYNNYS_VERO_OSANSTULO = 500;

* Muu ansiotulo (e/v);
%LET MINIMI_VERO_MUUANSTULO = 0;
%LET MAKSIMI_VERO_MUUANSTULO = 0;
%LET KYNNYS_VERO_MUUANSTULO = 500; 

* Osinkotulo pääomatulona (e/v);
%LET MINIMI_VERO_OSINKOTULO = 0;
%LET MAKSIMI_VERO_OSINKOTULO = 0;  
%LET KYNNYS_VERO_OSINKOTULO = 1000;

* Vuokratulot vakituisesta asunnosta (e/v);
%LET MINIMI_VERO_VUOKRATULO = 0;
%LET MAKSIMI_VERO_VUOKRATULO = 0;
%LET KYNNYS_VERO_VUOKRATULO = 500;

* Veronalaiset korkotulot (e/v);
%LET MINIMI_VERO_KORKOTULO = 0;
%LET MAKSIMI_VERO_KORKOTULO = 0;
%LET KYNNYS_VERO_KORKOTULO = 500; 

* Muu pääomatulo (e/v);
%LET MINIMI_VERO_MUUPOTULO = 0;
%LET MAKSIMI_VERO_MUUPOTULO = 0; 
%LET KYNNYS_VERO_MUUPOTULO = 500;

* Nettopalkka (e/kk), jos halutaan laskea käänteisfunktiolla bruttotulot;
%LET MINIMI_VERO_NETTOPALKKA = 0;
%LET MAKSIMI_VERO_NETTOPALKKA = 0;
%LET KYNNYS_VERO_NETTOPALKKA = 1000;

* Tuloaskel, jolla tuloa korotetaan 
  marginaaliveroastetta laskettaessa (e/v);
%LET MINIMI_VERO_ASKEL = 1;
%LET MAKSIMI_VERO_ASKEL = 1; 
%LET KYNNYS_VERO_ASKEL = 1; 

* Vakituinen asunto varallisuuden osana (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_VAKASU = 1;
%LET MAKSIMI_VERO_VAKASU = 1;

* Nettovarallisuus (e);
%LET MINIMI_VERO_NETTOVARALL = 300000;
%LET MAKSIMI_VERO_NETTOVARALL = 300000;
%LET KYNNYS_VERO_NETTOVARALL = 50000; */

/******************************************************/

* Tulonhankkimiskulut (e/v);
%LET MINIMI_VERO_TULONHANKKULUT = 0;
%LET MAKSIMI_VERO_TULONHANKKULUT = 0;
%LET KYNNYS_VERO_TULONHANKKULUT = 100;

* Ay-jäsenmaksut (e/v);
%LET MINIMI_VERO_AYMAKSUT = 0;
%LET MAKSIMI_VERO_AYMAKSUT = 0; 
%LET KYNNYS_VERO_AYMAKSUT = 100;

* Työmatkakulut (e/v);
%LET MINIMI_VERO_TYOMATKAKULUT = 0;
%LET MAKSIMI_VERO_TYOMATKAKULUT = 0; 
%LET KYNNYS_VERO_TYOMATKAKULUT = 100;

* Työasuntovähennykseen oikeuttavat kuukaudet (1-12);
%LET MINIMI_VERO_KUUKAUDET = 0;
%LET MAKSIMI_VERO_KUUKAUDET = 0;
%LET KYNNYS_VERO_KUUKAUDET = 1;

* Työasuntovähennykseen oikeuttava vuokra (e/kk); 
%LET MINIMI_VERO_VUOKRA = 0;
%LET MAKSIMI_VERO_VUOKRA = 0; 
%LET KYNNYS_VERO_VUOKRA = 500;

* Elatusmaksut (e/v);
%LET MINIMI_VERO_ELMAKSUT = 0;
%LET MAKSIMI_VERO_ELMAKSUT = 0;
%LET KYNNYS_VERO_ELMAKSUT = 500;

* Pääomatulon hankkimisesta aiheutuvat menot (e/v);
%LET MINIMI_VERO_POVAHENN = 0;
%LET MAKSIMI_VERO_POVAHENN = 0;
%LET KYNNYS_VERO_POVAHENN = 500;

* Asuntolainan korot (ei ensiasunto) (e/v);
%LET MINIMI_VERO_ASKOROT = 0;
%LET MAKSIMI_VERO_ASKOROT = 0;
%LET KYNNYS_VERO_ASKOROT = 100;

* Ensiasuntoon kohdistuvan lainan korot (e/v);
%LET MINIMI_VERO_ENSASKOROT = 0;
%LET MAKSIMI_VERO_ENSASKOROT = 0;
%LET KYNNYS_VERO_ENSASKOROT = 100;

* Kulutusluoton korot (e/v);
%LET MINIMI_VERO_KULKOROT = 0;
%LET MAKSIMI_VERO_KULKOROT = 0;
%LET KYNNYS_VERO_KULKOROT = 100; 

* Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-) (e/v);
%LET MINIMI_VERO_ELVAKMAKSU = 0;
%LET MAKSIMI_VERO_ELVAKMAKSU = 0; 
%LET KYNNYS_VERO_ELVAKMAKSU = 100;

* Sairauskulut (e/v);
%LET MINIMI_VERO_SAIRKULUT = 0;
%LET MAKSIMI_VERO_SAIRKULUT = 0; 
%LET KYNNYS_VERO_SAIRKULUT = 500;

* Kotitalousvähennykseen oikeuttavat menot (e/v);
%LET MINIMI_VERO_KOTITMENO = 0;
%LET MAKSIMI_VERO_KOTITMENO = 0;
%LET KYNNYS_VERO_KOTITMENO = 250;

* Muita vähennyksiä tulosta verotuksessa (e/v) (vuodesta 2023 alkaen); 
%LET MINIMI_VERO_MUUVAH = 0;
%LET MAKSIMI_VERO_MUUVAH = 0;
%LET KYNNYS_VERO_MUUVAH = 100;

* Muita vähennyksiä tulosta valtionverotuksessa (e/v); 
%LET MINIMI_VERO_MUUVAHVALT = 0;
%LET MAKSIMI_VERO_MUUVAHVALT = 0;
%LET KYNNYS_VERO_MUUVAHVALT = 100;

* Muita vähennyksiä tulosta kunnallisverotuksessa (e/v);  
%LET MINIMI_VERO_MUUVAHKUNN = 0;
%LET MAKSIMI_VERO_MUUVAHKUNN = 0; 
%LET KYNNYS_VERO_MUUVAHKUNN = 100;

/******************************************************/

* Onko puolisoa (0 = ei puolisoa, 1 = on puoliso);
%LET MINIMI_VERO_PUOLISO = 0; 
%LET MAKSIMI_VERO_PUOLISO = 0;

* Ikä (vuosina);
%LET MINIMI_VERO_IKA = 30; 
%LET MAKSIMI_VERO_IKA = 30;
 
* Huollettavina olevien alaikäisten lasten lukumäärä;
%LET MINIMI_VERO_LAPSIA = 0; 
%LET MAKSIMI_VERO_LAPSIA = 0;

* Elatusvellvollisten lasten lukumäärä; 
%LET MINIMI_VERO_EVLAPSIA = 0; 
%LET MAKSIMI_VERO_EVLAPSIA = 0;

* Onko opiskelija (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_OPISK = 0; 
%LET MAKSIMI_VERO_OPISK = 0;

* Onko yrittäjä (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_YRIT = 0; 
%LET MAKSIMI_VERO_YRIT = 0;

* Vamman haitta-aste (1-100);
%LET MINIMI_VERO_INVPROS = 0; 
%LET MAKSIMI_VERO_INVPROS = 0;
%LET KYNNYS_VERO_INVPROS = 50;

* Oikeus invalidivähennykseen eläketulosta vuonna 1982 (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_INVOIKEUS82 = 0;
%LET MAKSIMI_VERO_INVOIKEUS82 = 0;

* Työttömyyskuukaudet (1-12);
%LET MINIMI_VERO_TYOTKUUK = 0; 
%LET MAKSIMI_VERO_TYOTKUUK = 0;

* Puolison alijäämähyvitys (e/v);
%LET MINIMI_VERO_PUOLALIJ = 0; 
%LET MAKSIMI_VERO_PUOLALIJ = 0;
%LET KYNNYS_VERO_PUOLALIJ = 200;

* Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_KUNNPROS = 7.54; 
%LET MAKSIMI_VERO_KUNNPROS = 7.54;
%LET KYNNYS_VERO_KUNNPROS = 1;

* Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_KIRKPROS = 1.00; 
%LET MAKSIMI_VERO_KIRKPROS = 1.00;
%LET KYNNYS_VERO_KIRKPROS = 0.10;

* Käytetäänkö keskimääräistä kunnallis- ja kirkollisveroprosenttia (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_KESKIM = 1; 
%LET MAKSIMI_VERO_KESKIM = 1;

* Kuuluuko kirkkoon (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_KIRKOSSA = 1; 
%LET MAKSIMI_VERO_KIRKOSSA = 1;

/******************************************************/

* Vaihtoehtoinen alempi osuus (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_VAIHT = 1;
%LET MAKSIMI_VERO_VAIHT = 1;

* Jaettava yritystulo (e/v);
%LET MINIMI_VERO_YTULO = 0;
%LET MAKSIMI_VERO_YTULO = 0;
%LET KYNNYS_VERO_YTULO = 5000;

* Yritysvarallisuus/Osakkeiden arvo (e);
%LET MINIMI_VERO_YRITVARALL = 0;
%LET MAKSIMI_VERO_YRITVARALL = 0;
%LET KYNNYS_VERO_YRITVARALL = 50000;

* Yrityksessä maksetut palkat;
%LET MINIMI_VERO_YPALKKA = 0;
%LET MAKSIMI_VERO_YPALKKA = 0;
%LET KYNNYS_VERO_YPALKKA = 2000;

* Osinkotulo (e/v);
%LET MINIMI_VERO_OTULO = 0;
%LET MAKSIMI_VERO_OTULO = 0;
%LET KYNNYS_VERO_OTULO = 5000;

* Onko julk.osinko osuuspääoman korkoa? (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_OSPKORKO = 0;
%LET MAKSIMI_VERO_OSPKORKO = 0;

* Osinko julk. noteeratusta yhtiöstä (e/v);
%LET MINIMI_VERO_JULKOSINKO = 0;
%LET MAKSIMI_VERO_JULKOSINKO = 0;
%LET KYNNYS_VERO_JULKOSINKO = 5000;

* Muu osinko (e/v);
%LET MINIMI_VERO_EIJULKOSINKO = 0;
%LET MAKSIMI_VERO_EIJULKOSINKO = 0;
%LET KYNNYS_VERO_EIJULKOSINKO = 5000;

* Muiden osakkeiden matemaattinen arvo (e);
%LET MINIMI_VERO_OSAKKARVO = 0;
%LET MAKSIMI_VERO_OSAKKARVO = 0;
%LET KYNNYS_VERO_OSAKKARVO = 10000;

/******************************************************/

/* 2.2 Pienituloisemman puolison fiktiivinen data */

* Palkkatulo (e/v);
%LET MINIMI_VERO_PPTULO = 20000;
%LET MAKSIMI_VERO_PPTULO = 20000; 
%LET KYNNYS_VERO_PPTULO = 5000;

* Merityötulo (e/v);
%LET MINIMI_VERO_PMERITULO = 0;
%LET MAKSIMI_VERO_PMERITULO = 0; 
%LET KYNNYS_VERO_PMERITULO = 200;

* Muu työtulo kuin palkkatulo (e/v);
%LET MINIMI_VERO_PMTULO = 0;
%LET MAKSIMI_VERO_PMTULO = 0; 
%LET KYNNYS_VERO_PMTULO = 100;

* Päivärahatulo (e/v);
%LET MINIMI_VERO_PPRAHATULO = 0;
%LET MAKSIMI_VERO_PPRAHATULO = 0;
%LET KYNNYS_VERO_PPRAHATULO = 1000;

* Eläketulo (e/v);
%LET MINIMI_VERO_PETULO = 0;
%LET MAKSIMI_VERO_PETULO = 0;
%LET KYNNYS_VERO_PETULO = 1000;

* Opintoraha (e/v);
%LET MINIMI_VERO_POPRAHA = 0;
%LET MAKSIMI_VERO_POPRAHA = 0;
%LET KYNNYS_VERO_POPRAHA = 100;

* Osinkotulo ansiotulona (e/v);
%LET MINIMI_VERO_POSANSTULO = 0;
%LET MAKSIMI_VERO_POSANSTULO = 0;  
%LET KYNNYS_VERO_POSANSTULO = 500;

* Muu ansiotulo (e/v);
%LET MINIMI_VERO_PMUUANSTULO = 0;
%LET MAKSIMI_VERO_PMUUANSTULO = 0;
%LET KYNNYS_VERO_PMUUANSTULO = 500; 

* Osinkotulo pääomatulona (e/v);
%LET MINIMI_VERO_POSINKOTULO = 0;
%LET MAKSIMI_VERO_POSINKOTULO = 0;  
%LET KYNNYS_VERO_POSINKOTULO = 500;

* Vuokratulot vakituisesta asunnosta (e/v);
%LET MINIMI_VERO_PVUOKRATULO = 0;
%LET MAKSIMI_VERO_PVUOKRATULO = 0;
%LET KYNNYS_VERO_PVUOKRATULO = 500;

* Veronalaiset korkotulot (e/v);
%LET MINIMI_VERO_PKORKOTULO = 0;
%LET MAKSIMI_VERO_PKORKOTULO = 0;
%LET KYNNYS_VERO_PKORKOTULO = 500; 

* Muu pääomatulo (e/v);
%LET MINIMI_VERO_PMUUPOTULO = 0;
%LET MAKSIMI_VERO_PMUUPOTULO = 0; 
%LET KYNNYS_VERO_PMUUPOTULO = 500;

* Vakituinen asunto varallisuuden osana (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PVAKASU = 0;
%LET MAKSIMI_VERO_PVAKASU = 0;

* Nettovarallisuus (e);
%LET MINIMI_VERO_PNETTOVARALL = 0;
%LET MAKSIMI_VERO_PNETTOVARALL = 0;
%LET KYNNYS_VERO_PNETTOVARALL = 50000;

/******************************************************/

* Tulonhankkimiskulut (e/v);
%LET MINIMI_VERO_PTULONHANKKULUT = 0;
%LET MAKSIMI_VERO_PTULONHANKKULUT = 0;
%LET KYNNYS_VERO_PTULONHANKKULUT = 100;

* Ay-jäsenmaksut (e/v);
%LET MINIMI_VERO_PAYMAKSUT = 0;
%LET MAKSIMI_VERO_PAYMAKSUT = 0; 
%LET KYNNYS_VERO_PAYMAKSUT = 100;

* Työmatkakulut (e/v);
%LET MINIMI_VERO_PTYOMATKAKULUT = 0;
%LET MAKSIMI_VERO_PTYOMATKAKULUT = 0; 
%LET KYNNYS_VERO_PTYOMATKAKULUT = 100;

* Työasuntovähennykseen oikeuttavat kuukaudet (1-12);
%LET MINIMI_VERO_PKUUKAUDET = 0;
%LET MAKSIMI_VERO_PKUUKAUDET = 0;
%LET KYNNYS_VERO_PKUUKAUDET = 1;

* Työasuntovähennykseen oikeuttava vuokra (e/kk); 
%LET MINIMI_VERO_PVUOKRA = 0;
%LET MAKSIMI_VERO_PVUOKRA = 0; 
%LET KYNNYS_VERO_PVUOKRA = 500;

* Elatusmaksut (e/v);
%LET MINIMI_VERO_PELMAKSUT = 0;
%LET MAKSIMI_VERO_PELMAKSUT = 0;
%LET KYNNYS_VERO_PELMAKSUT = 500;

* Pääomatulon hankkimisesta aiheuttavat menot (e/v);
%LET MINIMI_VERO_PPOVAHENN = 0;
%LET MAKSIMI_VERO_PPOVAHENN = 0;
%LET KYNNYS_VERO_PPOVAHENN = 500;

* Asunto- ja opintolainan korot (e/v);
%LET MINIMI_VERO_PASKOROT = 0;
%LET MAKSIMI_VERO_PASKOROT = 0;
%LET KYNNYS_VERO_PASKOROT = 100;

* Ensiasuntoon kohdistuvan luoton korot (e/v);
%LET MINIMI_VERO_PENSASKOROT = 0;
%LET MAKSIMI_VERO_PENSASKOROT = 0; 
%LET KYNNYS_VERO_PENSASKOROT = 100;

* Kulutusluoton korot (e/v);
%LET MINIMI_VERO_PKULKOROT = 0;
%LET MAKSIMI_VERO_PKULKOROT = 0;
%LET KYNNYS_VERO_PKULKOROT = 100; 

* Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-) (e/v);
%LET MINIMI_VERO_PELVAKMAKSU = 0;
%LET MAKSIMI_VERO_PELVAKMAKSU = 0; 
%LET KYNNYS_VERO_PELVAKMAKSU = 100;

* Kotitalousvähennykseen oikeuttavat menot (e/v);
%LET MINIMI_VERO_PKOTITMENO = 0;
%LET MAKSIMI_VERO_PKOTITMENO = 0;
%LET KYNNYS_VERO_PKOTITMENO = 250;

* Muita vähennyksiä tulosta verotuksessa (e/v) (vuodesta 2023 alkaen); 
%LET MINIMI_VERO_PMUUVAH = 0;
%LET MAKSIMI_VERO_PMUUVAH = 0;
%LET KYNNYS_VERO_PMUUVAH = 100;

* Muita vähennyksiä tulosta valtionverotuksessa (e/v); 
%LET MINIMI_VERO_PMUUVAHVALT = 0;
%LET MAKSIMI_VERO_PMUUVAHVALT = 0;
%LET KYNNYS_VERO_PMUUVAHVALT = 100;

* Muita vähennyksiä tulosta kunnallisverotuksessa (e/v);  
%LET MINIMI_VERO_PMUUVAHKUNN = 0;
%LET MAKSIMI_VERO_PMUUVAHKUNN = 0; 
%LET KYNNYS_VERO_PMUUVAHKUNN = 100;

/******************************************************/

* Ikä (vuosina);
%LET MINIMI_VERO_PIKA = 30; 
%LET MAKSIMI_VERO_PIKA = 30;
 
* Elatusvellvollisten lasten lukumäärä; 
%LET MINIMI_VERO_PEVLAPSIA = 0; 
%LET MAKSIMI_VERO_PEVLAPSIA = 0;

* Onko opiskelija (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_POPISK = 0; 
%LET MAKSIMI_VERO_POPISK = 0;

* Onko yrittäjä (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PYRIT = 0; 
%LET MAKSIMI_VERO_PYRIT = 0;

* Vamman haitta-aste (1-100);
%LET MINIMI_VERO_PINVPROS = 0; 
%LET MAKSIMI_VERO_PINVPROS = 0;
%LET KYNNYS_VERO_PINVPROS = 50;

* Oikeus invalidivähennykseen eläketulosta vuonna 1982 (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PINVOIKEUS82 = 0;
%LET MAKSIMI_VERO_PINVOIKEUS82 = 0;

* Työttömyyskuukaudet (1-12);
%LET MINIMI_VERO_PTYOTKUUK = 0; 
%LET MAKSIMI_VERO_PTYOTKUUK = 0;

* Puolison alijäämähyvitys (e/v);
%LET MINIMI_VERO_PPUOLALIJ = 0; 
%LET MAKSIMI_VERO_PPUOLALIJ = 0;
%LET KYNNYS_VERO_PPUOLALIJ = 200;

* Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_PKUNNPROS = 7.54; 
%LET MAKSIMI_VERO_PKUNNPROS = 7.54;

* Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_PKIRKPROS = 1.00; 
%LET MAKSIMI_VERO_PKIRKPROS = 1.00;

* Käytetäänkö keskimääräistä kunnallis-, ja kirkollisveroprosenttia (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PKESKIM = 1; 
%LET MAKSIMI_VERO_PKESKIM = 1;

* Kuuluuko kirkkoon (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PKIRKOSSA = 1; 
%LET MAKSIMI_VERO_PKIRKOSSA = 1;

/******************************************************/

%END;


/* 3. Fiktiivisen aineiston luominen ja simulointi */

/* 3.1 Generoidaan data makromuuttujien arvojen mukaisesti */ 

DATA OUTPUT.&TULOSNIMI_VE;

DO VERO_VUOSI = &MINIMI_VERO_VUOSI TO &MAKSIMI_VERO_VUOSI;
DO VERO_PTULO = &MINIMI_VERO_PTULO TO &MAKSIMI_VERO_PTULO BY &KYNNYS_VERO_PTULO; 
DO VERO_MERITULO = &MINIMI_VERO_MERITULO TO &MAKSIMI_VERO_MERITULO BY &KYNNYS_VERO_MERITULO; 
DO VERO_MTULO = &MINIMI_VERO_MTULO TO &MAKSIMI_VERO_MTULO BY &KYNNYS_VERO_MTULO;
DO VERO_PRAHATULO = &MINIMI_VERO_PRAHATULO TO &MAKSIMI_VERO_PRAHATULO BY &KYNNYS_VERO_PRAHATULO; 
DO VERO_ETULO = &MINIMI_VERO_ETULO TO &MAKSIMI_VERO_ETULO BY &KYNNYS_VERO_ETULO;
DO VERO_OPRAHA = &MINIMI_VERO_OPRAHA TO &MAKSIMI_VERO_OPRAHA BY &KYNNYS_VERO_OPRAHA;
DO VERO_OSANSTULO = &MINIMI_VERO_OSANSTULO TO &MAKSIMI_VERO_OSANSTULO BY &KYNNYS_VERO_OSANSTULO;  
DO VERO_MUUANSTULO = &MINIMI_VERO_MUUANSTULO TO &MAKSIMI_VERO_MUUANSTULO BY &KYNNYS_VERO_MUUANSTULO;
DO VERO_OSINKOTULO = &MINIMI_VERO_OSINKOTULO TO &MAKSIMI_VERO_OSINKOTULO BY &KYNNYS_VERO_OSINKOTULO;   
DO VERO_VUOKRATULO = &MINIMI_VERO_VUOKRATULO TO &MAKSIMI_VERO_VUOKRATULO BY &KYNNYS_VERO_VUOKRATULO;
DO VERO_KORKOTULO = &MINIMI_VERO_KORKOTULO TO &MAKSIMI_VERO_KORKOTULO BY &KYNNYS_VERO_KORKOTULO;
DO VERO_MUUPOTULO = &MINIMI_VERO_MUUPOTULO TO &MAKSIMI_VERO_MUUPOTULO BY &KYNNYS_VERO_MUUPOTULO;
DO VERO_NETTOPALKKA = &MINIMI_VERO_NETTOPALKKA TO &MAKSIMI_VERO_NETTOPALKKA BY &KYNNYS_VERO_NETTOPALKKA;
DO VERO_ASKEL = &MINIMI_VERO_ASKEL TO &MAKSIMI_VERO_ASKEL BY &KYNNYS_VERO_ASKEL;
DO VERO_VAKASU = &MINIMI_VERO_VAKASU TO &MAKSIMI_VERO_VAKASU;
DO VERO_NETTOVARALL = &MINIMI_VERO_NETTOVARALL TO &MAKSIMI_VERO_NETTOVARALL BY &KYNNYS_VERO_NETTOVARALL;

DO VERO_TULONHANKKULUT = &MINIMI_VERO_TULONHANKKULUT TO &MAKSIMI_VERO_TULONHANKKULUT BY &KYNNYS_VERO_TULONHANKKULUT;
DO VERO_AYMAKSUT = &MINIMI_VERO_AYMAKSUT TO &MAKSIMI_VERO_AYMAKSUT BY &KYNNYS_VERO_AYMAKSUT; 
DO VERO_TYOMATKAKULUT = &MINIMI_VERO_TYOMATKAKULUT TO &MAKSIMI_VERO_TYOMATKAKULUT BY &KYNNYS_VERO_TYOMATKAKULUT; 
DO VERO_KUUKAUDET = &MINIMI_VERO_KUUKAUDET TO &MAKSIMI_VERO_KUUKAUDET BY &KYNNYS_VERO_KUUKAUDET;
DO VERO_VUOKRA = &MINIMI_VERO_VUOKRA TO &MAKSIMI_VERO_VUOKRA BY &KYNNYS_VERO_VUOKRA;
DO VERO_ELMAKSUT = &MINIMI_VERO_ELMAKSUT TO &MAKSIMI_VERO_ELMAKSUT BY &KYNNYS_VERO_ELMAKSUT;
DO VERO_POVAHENN = &MINIMI_VERO_POVAHENN TO &MAKSIMI_VERO_POVAHENN BY &KYNNYS_VERO_POVAHENN;
DO VERO_ASKOROT = &MINIMI_VERO_ASKOROT TO &MAKSIMI_VERO_ASKOROT BY &KYNNYS_VERO_ASKOROT;
DO VERO_ENSASKOROT = &MINIMI_VERO_ENSASKOROT TO &MAKSIMI_VERO_ENSASKOROT BY &KYNNYS_VERO_ENSASKOROT;
DO VERO_KULKOROT = &MINIMI_VERO_KULKOROT TO &MAKSIMI_VERO_KULKOROT BY &KYNNYS_VERO_KULKOROT;
DO VERO_ELVAKMAKSU = &MINIMI_VERO_ELVAKMAKSU TO &MAKSIMI_VERO_ELVAKMAKSU BY &KYNNYS_VERO_ELVAKMAKSU; 
DO VERO_SAIRKULUT = &MINIMI_VERO_SAIRKULUT TO &MAKSIMI_VERO_SAIRKULUT BY &KYNNYS_VERO_SAIRKULUT; 
DO VERO_KOTITMENO = &MINIMI_VERO_KOTITMENO TO &MAKSIMI_VERO_KOTITMENO BY &KYNNYS_VERO_KOTITMENO;
DO VERO_MUUVAH = &MINIMI_VERO_MUUVAH TO &MAKSIMI_VERO_MUUVAH BY &KYNNYS_VERO_MUUVAH;
DO VERO_MUUVAHVALT = &MINIMI_VERO_MUUVAHVALT TO &MAKSIMI_VERO_MUUVAHVALT BY &KYNNYS_VERO_MUUVAHVALT; 
DO VERO_MUUVAHKUNN = &MINIMI_VERO_MUUVAHKUNN TO &MAKSIMI_VERO_MUUVAHKUNN BY &KYNNYS_VERO_MUUVAHKUNN; 

DO VERO_PUOLISO = &MINIMI_VERO_PUOLISO TO &MAKSIMI_VERO_PUOLISO;
DO VERO_IKA = &MINIMI_VERO_IKA TO &MAKSIMI_VERO_IKA;
DO VERO_LAPSIA = &MINIMI_VERO_LAPSIA TO &MAKSIMI_VERO_LAPSIA;
DO VERO_EVLAPSIA = &MINIMI_VERO_EVLAPSIA TO &MAKSIMI_VERO_EVLAPSIA;
DO VERO_OPISK = &MINIMI_VERO_OPISK TO &MAKSIMI_VERO_OPISK;
DO VERO_YRIT = &MINIMI_VERO_YRIT TO &MAKSIMI_VERO_YRIT;
DO VERO_INVPROS = &MINIMI_VERO_INVPROS TO &MAKSIMI_VERO_INVPROS BY &KYNNYS_VERO_INVPROS;
DO VERO_INVOIKEUS82 = &MINIMI_VERO_INVOIKEUS82 TO &MAKSIMI_VERO_INVOIKEUS82;
DO VERO_TYOTKUUK = &MINIMI_VERO_TYOTKUUK TO &MAKSIMI_VERO_TYOTKUUK;
DO VERO_PUOLALIJ = &MINIMI_VERO_PUOLALIJ TO &MAKSIMI_VERO_PUOLALIJ BY &KYNNYS_VERO_PUOLALIJ;
DO VERO_KUNNPROS = &MINIMI_VERO_KUNNPROS TO &MAKSIMI_VERO_KUNNPROS BY &KYNNYS_VERO_KUNNPROS;
DO VERO_KIRKPROS = &MINIMI_VERO_KIRKPROS TO &MAKSIMI_VERO_KIRKPROS BY &KYNNYS_VERO_KIRKPROS;
DO VERO_KESKIM = &MINIMI_VERO_KESKIM TO &MAKSIMI_VERO_KESKIM;
DO VERO_KIRKOSSA = &MINIMI_VERO_KIRKOSSA TO &MAKSIMI_VERO_KIRKOSSA;

DO VERO_VAIHT = &MINIMI_VERO_VAIHT TO &MAKSIMI_VERO_VAIHT;
DO VERO_YTULO = &MINIMI_VERO_YTULO TO &MAKSIMI_VERO_YTULO BY &KYNNYS_VERO_YTULO;
DO VERO_YRITVARALL = &MINIMI_VERO_YRITVARALL TO &MAKSIMI_VERO_YRITVARALL BY &KYNNYS_VERO_YRITVARALL;
DO VERO_YPALKKA = &MINIMI_VERO_YPALKKA TO &MAKSIMI_VERO_YPALKKA BY &KYNNYS_VERO_YPALKKA;
DO VERO_OTULO = &MINIMI_VERO_OTULO TO &MAKSIMI_VERO_OTULO BY &KYNNYS_VERO_OTULO;
DO VERO_OSPKORKO = &MINIMI_VERO_OSPKORKO TO &MAKSIMI_VERO_OSPKORKO;
DO VERO_JULKOSINKO = &MINIMI_VERO_JULKOSINKO TO &MAKSIMI_VERO_JULKOSINKO BY &KYNNYS_VERO_JULKOSINKO;
DO VERO_EIJULKOSINKO = &MINIMI_VERO_EIJULKOSINKO TO &MAKSIMI_VERO_EIJULKOSINKO BY &KYNNYS_VERO_EIJULKOSINKO;
DO VERO_OSAKKARVO = &MINIMI_VERO_OSAKKARVO TO &MAKSIMI_VERO_OSAKKARVO BY &KYNNYS_VERO_OSAKKARVO;

/*************** Puolison data (luodaan, jos VERO_PUOLISO = 1) **************************/

%IF &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

DO VERO_PPTULO = &MINIMI_VERO_PPTULO TO &MAKSIMI_VERO_PPTULO BY &KYNNYS_VERO_PPTULO; 
DO VERO_PMERITULO = &MINIMI_VERO_PMERITULO TO &MAKSIMI_VERO_PMERITULO BY &KYNNYS_VERO_PMERITULO;
DO VERO_PMTULO = &MINIMI_VERO_PMTULO TO &MAKSIMI_VERO_PMTULO BY &KYNNYS_VERO_PMTULO;
DO VERO_PPRAHATULO = &MINIMI_VERO_PPRAHATULO TO &MAKSIMI_VERO_PPRAHATULO BY &KYNNYS_VERO_PPRAHATULO;  
DO VERO_PETULO = &MINIMI_VERO_PETULO TO &MAKSIMI_VERO_PETULO BY &KYNNYS_VERO_PETULO;
DO VERO_POPRAHA = &MINIMI_VERO_POPRAHA TO &MAKSIMI_VERO_POPRAHA BY &KYNNYS_VERO_POPRAHA;
DO VERO_POSANSTULO = &MINIMI_VERO_POSANSTULO TO &MAKSIMI_VERO_POSANSTULO BY &KYNNYS_VERO_POSANSTULO;  
DO VERO_PMUUANSTULO = &MINIMI_VERO_PMUUANSTULO TO &MAKSIMI_VERO_PMUUANSTULO BY &KYNNYS_VERO_PMUUANSTULO;
DO VERO_POSINKOTULO = &MINIMI_VERO_POSINKOTULO TO &MAKSIMI_VERO_POSINKOTULO BY &KYNNYS_VERO_POSINKOTULO;   
DO VERO_PVUOKRATULO = &MINIMI_VERO_PVUOKRATULO TO &MAKSIMI_VERO_PVUOKRATULO BY &KYNNYS_VERO_PVUOKRATULO;
DO VERO_PKORKOTULO = &MINIMI_VERO_PKORKOTULO TO &MAKSIMI_VERO_PKORKOTULO BY &KYNNYS_VERO_PKORKOTULO;
DO VERO_PMUUPOTULO = &MINIMI_VERO_PMUUPOTULO TO &MAKSIMI_VERO_PMUUPOTULO BY &KYNNYS_VERO_PMUUPOTULO;
DO VERO_PVAKASU = &MINIMI_VERO_PVAKASU TO &MAKSIMI_VERO_PVAKASU;
DO VERO_PNETTOVARALL = &MINIMI_VERO_PNETTOVARALL TO &MAKSIMI_VERO_PNETTOVARALL BY &KYNNYS_VERO_PNETTOVARALL;

DO VERO_PTULONHANKKULUT = &MINIMI_VERO_PTULONHANKKULUT TO &MAKSIMI_VERO_PTULONHANKKULUT BY &KYNNYS_VERO_PTULONHANKKULUT;
DO VERO_PAYMAKSUT = &MINIMI_VERO_PAYMAKSUT TO &MAKSIMI_VERO_PAYMAKSUT BY &KYNNYS_VERO_PAYMAKSUT; 
DO VERO_PTYOMATKAKULUT = &MINIMI_VERO_PTYOMATKAKULUT TO &MAKSIMI_VERO_PTYOMATKAKULUT BY &KYNNYS_VERO_PTYOMATKAKULUT; 
DO VERO_PKUUKAUDET = &MINIMI_VERO_PKUUKAUDET TO &MAKSIMI_VERO_PKUUKAUDET BY &KYNNYS_VERO_PKUUKAUDET;
DO VERO_PVUOKRA = &MINIMI_VERO_PVUOKRA TO &MAKSIMI_VERO_PVUOKRA BY &KYNNYS_VERO_PVUOKRA;
DO VERO_PELMAKSUT = &MINIMI_VERO_PELMAKSUT TO &MAKSIMI_VERO_PELMAKSUT BY &KYNNYS_VERO_PELMAKSUT;
DO VERO_PPOVAHENN = &MINIMI_VERO_PPOVAHENN TO &MAKSIMI_VERO_PPOVAHENN BY &KYNNYS_VERO_PPOVAHENN;
DO VERO_PASKOROT = &MINIMI_VERO_PASKOROT TO &MAKSIMI_VERO_PASKOROT BY &KYNNYS_VERO_PASKOROT;
DO VERO_PENSASKOROT = &MINIMI_VERO_PENSASKOROT TO &MAKSIMI_VERO_PENSASKOROT BY &KYNNYS_VERO_PENSASKOROT;
DO VERO_PKULKOROT = &MINIMI_VERO_PKULKOROT TO &MAKSIMI_VERO_PKULKOROT BY &KYNNYS_VERO_PKULKOROT;
DO VERO_PELVAKMAKSU = &MINIMI_VERO_PELVAKMAKSU TO &MAKSIMI_VERO_PELVAKMAKSU BY &KYNNYS_VERO_PELVAKMAKSU; 
DO VERO_PKOTITMENO = &MINIMI_VERO_PKOTITMENO TO &MAKSIMI_VERO_PKOTITMENO BY &KYNNYS_VERO_PKOTITMENO;
DO VERO_PMUUVAH = &MINIMI_VERO_PMUUVAH TO &MAKSIMI_VERO_PMUUVAH BY &KYNNYS_VERO_PMUUVAH; 
DO VERO_PMUUVAHVALT = &MINIMI_VERO_PMUUVAHVALT TO &MAKSIMI_VERO_PMUUVAHVALT BY &KYNNYS_VERO_PMUUVAHVALT; 
DO VERO_PMUUVAHKUNN = &MINIMI_VERO_PMUUVAHKUNN TO &MAKSIMI_VERO_PMUUVAHKUNN BY &KYNNYS_VERO_PMUUVAHKUNN; 

DO VERO_PIKA = &MINIMI_VERO_PIKA TO &MAKSIMI_VERO_PIKA;
DO VERO_PEVLAPSIA = &MINIMI_VERO_PEVLAPSIA TO &MAKSIMI_VERO_PEVLAPSIA;
DO VERO_POPISK = &MINIMI_VERO_POPISK TO &MAKSIMI_VERO_POPISK;
DO VERO_PYRIT = &MINIMI_VERO_PYRIT TO &MAKSIMI_VERO_PYRIT;
DO VERO_PINVPROS = &MINIMI_VERO_PINVPROS TO &MAKSIMI_VERO_PINVPROS BY &KYNNYS_VERO_PINVPROS;
DO VERO_PTYOTKUUK = &MINIMI_VERO_PTYOTKUUK TO &MAKSIMI_VERO_PTYOTKUUK;
DO VERO_PINVOIKEUS82 = &MINIMI_VERO_PINVOIKEUS82 TO &MAKSIMI_VERO_PINVOIKEUS82;
DO VERO_PPUOLALIJ = &MINIMI_VERO_PPUOLALIJ TO &MAKSIMI_VERO_PPUOLALIJ BY &KYNNYS_VERO_PPUOLALIJ;
DO VERO_PKIRKPROS = &MINIMI_VERO_PKIRKPROS TO &MAKSIMI_VERO_PKIRKPROS;
DO VERO_PKUNNPROS = &MINIMI_VERO_PKUNNPROS TO &MAKSIMI_VERO_PKUNNPROS;
DO VERO_PKESKIM = &MINIMI_VERO_PKESKIM TO &MAKSIMI_VERO_PKESKIM;
DO VERO_PKIRKOSSA = &MINIMI_VERO_PKIRKOSSA TO &MAKSIMI_VERO_PKIRKOSSA;

%END;

/* Lasketaan mahdollinen indeksiin perustuva inflaatiokorjaus */
%InfKerroin_ESIM(&AVUOSI, VERO_VUOSI, &INF);

OUTPUT;

END;END;END;END;END;END;END;END;END;END;END;END;END;END;
END;END;END;END;END;END;END;END;END;END;END;END;END;END;END;
END;END;END;END;END;END;END;END;END;END;END;END;END;END;
END;END;END;END;END;END;END;END;END;END;END;END;END;

%IF &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

	END;END;END;END;END;END;END;END;END;END;END;END;END;
	END;END;END;END;END;END;END;END;END;END;END;END;END;END;
	END;END;END;END;END;END;END;END;END;END;END;END;END;END;

%END;

RUN;

%IF &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

	DATA OUTPUT.&TULOSNIMI_VE; 
	SET OUTPUT.&TULOSNIMI_VE;

	ARRAY PUOLISO VERO_PPTULO--VERO_PKIRKOSSA;
		DO OVER PUOLISO;
			IF VERO_PUOLISO = 0 THEN PUOLISO = .;
		END;
	RUN;

%END;

%MEND Generoi_Muuttujat;

%Generoi_Muuttujat;


/* 3.2 Simuloidaan valitut muuttujat esimerkkiaineistolla */

%MACRO Vero_Simuloi_Esimerkki;

/* VERO-mallin parametrit */

/* Muuttujat, joihin haetaan lista mallin käyttämistä lakiparametreistä */
%LOCAL VERO_PARAM VERO_MUUNNOS VERO2_PARAM VERO2_MUUNNOS VERO_JOHDETUT;

/* Haetaan mallin käyttämien lakiparametrien nimet */
%HaeLokaalit(VERO_PARAM, VERO);
%HaeLaskettavatLokaalit(VERO_MUUNNOS, VERO);
%LOCAL KirkKerroin KunnKerroin;

/* Haetaan varallisuusveron käyttämien lakiparametrien nimet */
%HaeLokaalit(VERO2_PARAM, VERO_VARALL);
%HaeLaskettavatLokaalit(VERO2_MUUNNOS, VERO_VARALL, indikaattori='z');

/* Haetaan johdettavien muuttujien nimet */
%HaeLaskettavatLokaalit(VERO_JOHDETUT, VERO, indikaattori='j');

/* Luodaan tyhjät lokaalit muuttujat lakiparametien hakua varten */
%LOCAL &VERO_PARAM &VERO2_PARAM &VERO_JOHDETUT;

DATA OUTPUT.&TULOSNIMI_VE;
SET OUTPUT.&TULOSNIMI_VE;

/* 3.2.1 Lasketaan palkkaverotuksen tuloverot */

IF VERO_PTULO > 0 THEN DO;
%TuloVerot_SimpleS(TULOVERO, VERO_VUOSI, INF, VERO_PTULO, VERO_IKA);

	/* Verojen osuus tuloista */
	VOSUUSPTULO = (TULOVERO / VERO_PTULO) * 100;

END;

/* 3.2.2 Lasketaan käänteisfunktiolla nettokuukausituloa vastaava bruttokuukausitulo */

IF VERO_NETTOPALKKA > 0 THEN DO;
	%BruttotuloS(BRUTTOTULO, VERO_VUOSI, INF, VERO_NETTOPALKKA, VERO_IKA);

	/* Verojen osuus tuloista */
	VOSUUSNKTULO = (SUM(BRUTTOTULO, -VERO_NETTOPALKKA) / BRUTTOTULO) * 100;

END;

/* 3.2.3 Lasketaan marginaaliveroaste */

IF VERO_PTULO > 0 THEN DO;
	%TuloVerot_SimpleMargS(MARGINAALIVERO, VERO_VUOSI, INF, VERO_PTULO, VERO_ASKEL, VERO_IKA);

	MARGINAALIVEROASTE = MARGINAALIVERO * 100;

	DROP MARGINAALIVERO;

END;

/* 3.2.4 Lasketaan eläketulonverot */

IF VERO_ETULO > 0 THEN DO;
	%TuloVerot_Simple_ElakeS(TULOVERO_ELAKE, VERO_VUOSI, INF, VERO_PUOLISO, VERO_ETULO);

	/* Verojen osuus tuloista */
	VOSUUSETULO = (TULOVERO_ELAKE / VERO_ETULO) * 100;

END;

/* 3.2.5 Lasketaan tuloverot kun tulot ovat työttömyysturvaa tai muuta vastaavaa sosiaalietuutta */ 

IF VERO_PRAHATULO > 0 THEN DO;
	%TuloVerot_Simple_PRahaS(TULOVERO_PRAHA, VERO_VUOSI, INF, VERO_PRAHATULO);

	/* Verojen osuus tuloista */
	VOSUUSPRAHATULO = (TULOVERO_PRAHA / VERO_PRAHATULO) * 100;

END;

/* 3.2.6 Veromalli */

* Johdettuja tulokäsitteitä ja vähennyksiä ym. (e/v);

* Kokonaistulot;
KOKONTULO = SUM(VERO_PTULO, VERO_MERITULO, VERO_PRAHATULO, VERO_MTULO, VERO_ETULO, VERO_OPRAHA, VERO_OSANSTULO, VERO_MUUANSTULO, VERO_OSINKOTULO, VERO_VUOKRATULO, VERO_KORKOTULO, VERO_MUUPOTULO);

* Ansiotulot (ilman yhtiöveron hyvitystä);
ANSIOTULO = SUM(VERO_PTULO, VERO_MERITULO, VERO_PRAHATULO, VERO_MTULO, VERO_ETULO, VERO_OPRAHA, VERO_OSANSTULO, VERO_MUUANSTULO);

*Pääomatulot (ilman yhtiöveron hyvitystä);
POTULO = SUM(VERO_OSINKOTULO, VERO_VUOKRATULO, VERO_KORKOTULO, VERO_MUUPOTULO);

PUHDPOTULO = SUM(POTULO, -VERO_POVAHENN);

* Puhdas ansiotulo;
%TulonHankKulutS(TULHANKSUMS, VERO_VUOSI, INF, VERO_PTULO, VERO_TULONHANKKULUT, VERO_AYMAKSUT, VERO_TYOMATKAKULUT, VERO_KUUKAUDET);
%TulonHankKulutS(TULHANKSUMSM, VERO_VUOSI, INF, VERO_MERITULO, VERO_TULONHANKKULUT, 0, 0, VERO_KUUKAUDET);

%AsuntoVahennysS(ASUNTOVAH, VERO_VUOSI, INF, VERO_KUUKAUDET, VERO_VUOKRA);

PUHDANSTULO = MAX(SUM(ANSIOTULO, -TULHANKSUMS, -TULHANKSUMSM, -ASUNTOVAH), 0);

/* Vähennykset: */

/* Ansiotulovähennykset */
MUUANS2 = MAX(SUM(ANSIOTULO, -VERO_ETULO), 0);
%AnsVahS(ANS, VERO_VUOSI, INF, PUHDANSTULO, SUM(VERO_PTULO, VERO_MERITULO, VERO_MTULO)); /* 2023-2024 */
%KunnAnsVahS(KUNNANS, VERO_VUOSI, INF, PUHDANSTULO, MUUANS2, SUM(VERO_PTULO, VERO_MERITULO, VERO_MTULO), SUM(VERO_PTULO, VERO_MERITULO), KOKONTULO); /* -2022 */

/* Eläketulovähennykset */
%ElTulVahS(ELVAH, VERO_VUOSI, INF, VERO_ETULO, PUHDANSTULO); /* 2023- */
%ValtElTulVahS(ELVAHV, VERO_VUOSI, INF, VERO_ETULO, PUHDANSTULO, KOKONTULO);  /* -2022 */
%KunnElTulVahS(ELVELVAHK, VERO_VUOSI, INF, VERO_PUOLISO, 0, VERO_ETULO, PUHDANSTULO, KOKONTULO); /* -2022 */

/* Opintorahavähennykset */
%OpRahVahS(OPRAHVAH, VERO_VUOSI, INF, VERO_OPRAHA, PUHDANSTULO); /* 2023- */
%KunnOpRahVahS(OPRAHVAHK, VERO_VUOSI, INF, VERO_OPISK, VERO_OPRAHA, ANSIOTULO, PUHDANSTULO); /* -2022 */

/* Merityötulovähennykset */
%VerMeriVahS(MERIVAH, VERO_VUOSI, INF, VERO_MERITULO); /* 2023- */
%ValtVerMeriVahS(MERIVAHVAL, VERO_VUOSI, INF, VERO_MERITULO); /* -2022 */
%KunnVerMeriVahS(MERIVAHKUN, VERO_VUOSI, INF, VERO_MERITULO); /* -2022 */

/* Invalidivähennykset (-2022) */
%KunnVerInvVahS(INVVAH_K, VERO_VUOSI, INF, VERO_INVOIKEUS82, VERO_INVPROS, PUHDANSTULO, VERO_ETULO);
%ValtVerInvVahS(INVVAH, VERO_VUOSI, INF, VERO_INVPROS, VERO_ETULO);

/* Sosiaalivakuutusmaksut */
%TyoelMaksuS(TYOELMAKSU, VERO_VUOSI, INF, VERO_IKA, VERO_PTULO);
%TyotMaksuS(TYOTMAKSU, VERO_VUOSI, INF, VERO_IKA, VERO_PTULO);
%SvPrahaMaksuS(SPM, VERO_VUOSI, INF, VERO_IKA, SUM(VERO_PTULO, VERO_MERITULO));
%SvPRahaMaksuYS(SPMY, VERO_VUOSI, INF, VERO_IKA, 1, VERO_OSINKOTULO);
SPMAKSU = SUM(SPM, SPMY);

/* Perusvähennykset */
IF VERO_VUOSI >= 2023 THEN DO;
/* Verotettava tulo ennen ja jälkeen perusvähennyksen (2023-) */
	VEROTULOP = MAX(SUM(PUHDANSTULO, -TYOELMAKSU, -TYOTMAKSU, -SPMAKSU, -ANS, -MERIVAH, -ELVAH, -OPRAHVAH, -VERO_MUUVAH), 0);
	%PerVahS(PERVAH, VERO_VUOSI, INF, VEROTULOP);
	VEROTULO = MAX(SUM(VEROTULOP, -PERVAH), 0); 
	KUNNVERTULOSP = VEROTULO;
END;
ELSE DO;	
/* Verotettava tulo kunnallisverotuksessa ennen ja jälkeen perusvähennyksen (-2022) */
	%YhtHyvS(YHTHYVPO, VERO_VUOSI, INF, VERO_OSINKOTULO);
	IF VERO_VUOSI < 1993 THEN PA = SUM(KOKONTULO, YHTHYVPO, -TULHANKSUMS, -TULHANKSUMSM, -VERO_POVAHENN);
	ELSE PA = PUHDANSTULO;

	KUNNVEROTULO = MAX(SUM(PA, -TYOELMAKSU, -TYOTMAKSU, -SPMAKSU, -KUNNANS, -MERIVAHKUN, -ELVELVAHK, -OPRAHVAHK, -VERO_MUUVAHKUNN, -INVVAH_K), 0);
	IF KUNNVEROTULO < 0 THEN KUNNVEROTULO = 0;
	%KunnPerVahS(PERVAH_K, VERO_VUOSI, INF, KUNNVEROTULO);
	KUNNVERTULOSP = MAX(SUM(KUNNVEROTULO, -PERVAH_K), 0);
END;

/* Vähennyksiä veroista: */

/* Työtulovähennykset */
%TyotVahS(TYOTULVAH, VERO_VUOSI, INF, SUM(VERO_PTULO, VERO_MERITULO, VERO_MTULO, VERO_OSANSTULO), PUHDANSTULO, VERO_IKA, -(VERO_PUOLISO-1),  VERO_LAPSIA);

/* Valtionverotuksen työtulo- ja palkkavähennys (-1988) */
%ValtTyoTuloVahS(VALTTVAH, VERO_VUOSI, INF, ANSIOTULO, SUM(VERO_PTULO, VERO_MERITULO));

/* Valtionverotuksen elatusvelvollisuusvähennys */
%ValtVerElVelvVahS(VELVVAHV, VERO_VUOSI, INF, VERO_EVLAPSIA, VERO_ELMAKSUT);

/* Alijäämähyvitys */
%AlijHyvS(ALIJHYV, VERO_VUOSI, INF, VERO_PUOLISO, VERO_LAPSIA, SUM(POTULO, YHTHYVPO), VERO_POVAHENN, VERO_ASKOROT, VERO_ENSASKOROT, VERO_KULKOROT, VERO_PUOLALIJ);

/* Erityinen alijäämähyvitys */
%AlijHyvEritS(ALIJHYVERIT, VERO_VUOSI, INF, SUM(POTULO, YHTHYVPO), VERO_POVAHENN, VERO_ASKOROT, VERO_ENSASKOROT, VERO_ELVAKMAKSU);

/* Kotitalousvähennys */
%KotiTalVahS(KOTIVAH, VERO_VUOSI, INF, VERO_KOTITMENO);

/* Yhtiöveron hyvitys (-2004) */
IF VERO_VUOSI > 1992 THEN DO;
	%YhtHyvS(YHTHYVANS, VERO_VUOSI, INF, VERO_OSANSTULO);
END;
ELSE YHTHYVANS = 0;

YHTHYVYHT = SUM(YHTHYVANS, YHTHYVPO);

IF VERO_VUOSI < 1993 THEN DO;
	TEMPA = KOKONTULO; 
   	TEMPB = YHTHYVPO;
END;
ELSE DO;
	TEMPA = ANSIOTULO;
	TEMPB = 0;
END;

/* Valtionverotuksessa verotettava ansiotulo */
IF VERO_VUOSI >= 2023 THEN
	VALTVEROTULO = VEROTULO;
ELSE
	VALTVEROTULO = MAX(SUM(TEMPA, TEMPB, YHTHYVANS, -TULHANKSUMS, -TULHANKSUMSM, -MERIVAHVAL, -TYOELMAKSU, -TYOTMAKSU, -SPMAKSU, -ELVAHV, -VALTTVAH, -VERO_MUUVAHVALT), 0);

IF VERO_VUOSI < 1995 THEN TEMPC = VERO_KULKOROT;
ELSE TEMPC = 0;

/* Verotettava pääomatulo */
VEROPOTULO = MAX(SUM(POTULO, YHTHYVPO, -VERO_ASKOROT, VERO_ENSASKOROT, -VERO_POVAHENN, -TEMPC), 0); 

/* Verotettava tulo valtionverotuksessa yhteensä */
IF VERO_VUOSI >= 1993 THEN
	YHTVALTVEROTULO = SUM(VALTVEROTULO, VEROPOTULO); /* 1993- */
ELSE IF VERO_VUOSI <= 1992 THEN
	YHTVALTVEROTULO = VALTVEROTULO; /* -1992 */

/* Tuloverot ennen työtulovähennystä */
%ValtTuloVeroS(VALTTULOVERO, VERO_VUOSI, INF, VALTVEROTULO, 0);

/* Eläketulon lisävero */
IF VERO_VUOSI >= 2023 THEN DO;
	%ElakeLisaVeroS(ELAKELISAVERO, VERO_VUOSI, INF, VERO_ETULO, ELVAH);
END;
ELSE DO;
	%ElakeLisaVeroS(ELAKELISAVERO, VERO_VUOSI, INF, VERO_ETULO, ELVAHV);	
END;

VALTTULOVERO = SUM(VALTTULOVERO, ELAKELISAVERO);

/* Kunnallisvero*/
%KunnVeroS(KUNNVERO, VERO_VUOSI, INF, VERO_KESKIM, VERO_KUNNPROS, KUNNVERTULOSP);

/* Sairausvakuutusmaksu */
%SairVakMaksuS(SVMAKSU, VERO_VUOSI, INF, KUNNVERTULOSP, VERO_ETULO, SUM(VERO_PTULO, VERO_MERITULO, VERO_MTULO));

/* Kansaneläkevakuutusmaksu */
%KansElVakMaksuS(KEVMAKSU, VERO_VUOSI, INF, KUNNVERTULOSP, VERO_ETULO);

/* Kirkollisvero */
IF VERO_KIRKOSSA = 1 THEN DO;
	%KirkVeroS(KIRKVEROS, VERO_VUOSI, INF, VERO_KESKIM, VERO_KIRKPROS, KUNNVERTULOSP);
END;
ELSE KIRKVEROS = 0;

/* Pääomatulon vero */
%POTulonVeroEritS(POTULOVERO, VERO_VUOSI, INF, VERO_OSINKOTULO, SUM(VERO_VUOKRATULO, VERO_KORKOTULO, VERO_MUUPOTULO), SUM(VERO_POVAHENN, VERO_ASKOROT, VERO_ENSASKOROT), VERO_KULKOROT, VERO_ELVAKMAKSU);

/* Tuloverot työtulovähennyksen jälkeen (jaetaan eri verolajeille, jos vuosi > 2008) */
IF VERO_VUOSI > 2008 THEN DO;
%VahennJakoS(VALTTULOANSVERO, VERO_VUOSI, TYOTULVAH, 1, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);
%VahennJakoS(KUNNALLISVERO, VERO_VUOSI, TYOTULVAH, 2, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);
%VahennJakoS(SAIRAUSVAKUUTUSMAKSU, VERO_VUOSI, TYOTULVAH, 3, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);
%VahennJakoS(KELAVAKUUTUSMAKSU, VERO_VUOSI, TYOTULVAH, 4, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);
%VahennJakoS(KIRKOLLISVERO, VERO_VUOSI, TYOTULVAH, 5, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);
END;
	ELSE DO;
		VALTTULOANSVERO = MAX(SUM(VALTTULOVERO, -TYOTULVAH), 0);
		KUNNALLISVERO = KUNNVERO;
		SAIRAUSVAKUUTUSMAKSU = SVMAKSU;
		KELAVAKUUTUSMAKSU = KEVMAKSU;
		KIRKOLLISVERO = KIRKVEROS; 
	END;	

/* Tuloverot lapsivähennyksen jälkeen (2015-2017) */
%ValtVerLapsVahS(VALTLAPSVAH, VERO_VUOSI, INF,  -(VERO_PUOLISO-1), VERO_LAPSIA, SUM(PUHDANSTULO, PUHDPOTULO));

IF VERO_VUOSI > 2014 THEN DO;
		%VahennJakoS(VALTTULOANSVERO2, VERO_VUOSI, VALTLAPSVAH, 1, VALTTULOANSVERO, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);
		%VahennJakoS(KUNNALLISVERO2, VERO_VUOSI, VALTLAPSVAH, 2, VALTTULOANSVERO, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);
		%VahennJakoS(SAIRAUSVAKUUTUSMAKSU2, VERO_VUOSI, VALTLAPSVAH, 3, VALTTULOANSVERO, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);
		%VahennJakoS(KELAVAKUUTUSMAKSU2, VERO_VUOSI, VALTLAPSVAH, 4, VALTTULOANSVERO, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);
		%VahennJakoS(KIRKOLLISVERO2, VERO_VUOSI, VALTLAPSVAH, 5, VALTTULOANSVERO, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);
		%VahennJakoS(PAAOMAVERO2, VERO_VUOSI, VALTLAPSVAH, 6, VALTTULOANSVERO, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);
END;
ELSE DO;
		VALTTULOANSVERO2 = VALTTULOANSVERO;
		KUNNALLISVERO2 = KUNNALLISVERO;
		SAIRAUSVAKUUTUSMAKSU2 = SAIRAUSVAKUUTUSMAKSU;
		KELAVAKUUTUSMAKSU2 = KELAVAKUUTUSMAKSU;
		KIRKOLLISVERO2 = KIRKOLLISVERO; 
		PAAOMAVERO2 = POTULOVERO;
END;

/*  Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen */
VALTTULOINV = MAX(SUM(VALTTULOANSVERO2, -INVVAH, -VELVVAHV), 0);

/* Tuloverot kotitalousvähennyksen jälkeen */
%VahennJakoS(VALTTULOANSVERO3, VERO_VUOSI, KOTIVAH, 1, VALTTULOINV, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2, PAAOMAVERO2);
%VahennJakoS(KUNNALLISVERO3, VERO_VUOSI, KOTIVAH, 2, VALTTULOINV, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2, PAAOMAVERO2);
%VahennJakoS(SAIRAUSVAKUUTUSMAKSU3, VERO_VUOSI, KOTIVAH, 3, VALTTULOINV, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2, PAAOMAVERO2);
%VahennJakoS(KELAVAKUUTUSMAKSU3, VERO_VUOSI, KOTIVAH, 4, VALTTULOINV, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2, PAAOMAVERO2);
%VahennJakoS(KIRKOLLISVERO3, VERO_VUOSI, KOTIVAH, 5, VALTTULOINV, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2, PAAOMAVERO2);
%VahennJakoS(PAAOMAVERO3, VERO_VUOSI, KOTIVAH, 6, VALTTULOINV, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2, PAAOMAVERO2);

/* Tuloverot alijäämähyvityksen jälkeen */
%AlijHyvJakoS(VALTTULOANSVERO4, VERO_VUOSI, 1, ALIJHYV, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3);
%AlijHyvJakoS(KUNNALLISVERO4, VERO_VUOSI, 2, ALIJHYV, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3);
%AlijHyvJakoS(SAIRAUSVAKUUTUSMAKSU4, VERO_VUOSI, 3, ALIJHYV, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3);
%AlijHyvJakoS(KELAVAKUUTUSMAKSU4, VERO_VUOSI, 4, ALIJHYV, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3);
%AlijHyvJakoS(KIRKOLLISVERO4, VERO_VUOSI, 5, ALIJHYV, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3);

/* Tuloverot erityisen alijäämähyvityksen jälkeen */
%VahennJakoS(VALTTULOANSVERO5, VERO_VUOSI, ALIJHYVERIT, 1, VALTTULOANSVERO4, KUNNALLISVERO4, SAIRAUSVAKUUTUSMAKSU4, KELAVAKUUTUSMAKSU4, KIRKOLLISVERO4, 0);
%VahennJakoS(KUNNALLISVERO5, VERO_VUOSI, ALIJHYVERIT, 2, VALTTULOANSVERO4, KUNNALLISVERO4, SAIRAUSVAKUUTUSMAKSU4, KELAVAKUUTUSMAKSU4, KIRKOLLISVERO4, 0);
%VahennJakoS(SAIRAUSVAKUUTUSMAKSU5, VERO_VUOSI, ALIJHYVERIT, 3, VALTTULOANSVERO4, KUNNALLISVERO4, SAIRAUSVAKUUTUSMAKSU4, KELAVAKUUTUSMAKSU4, KIRKOLLISVERO4, 0);
%VahennJakoS(KELAVAKUUTUSMAKSU5, VERO_VUOSI, ALIJHYVERIT, 4, VALTTULOANSVERO4, KUNNALLISVERO4, SAIRAUSVAKUUTUSMAKSU4, KELAVAKUUTUSMAKSU4, KIRKOLLISVERO4, 0);
%VahennJakoS(KIRKOLLISVERO5, VERO_VUOSI, ALIJHYVERIT, 5, VALTTULOANSVERO4, KUNNALLISVERO4, SAIRAUSVAKUUTUSMAKSU4, KELAVAKUUTUSMAKSU4, KIRKOLLISVERO4, 0);

/* Ansiotulojen verot yhteensä */
ANSTULVEROT = SUM(VALTTULOANSVERO5, KUNNALLISVERO5, SAIRAUSVAKUUTUSMAKSU5, KELAVAKUUTUSMAKSU5, KIRKOLLISVERO5);

/* Varallisuusvero */
%VarallVeroS(VAVERO, VERO_VUOSI, INF, VERO_PUOLISO, VERO_LAPSIA, VERO_VAKASU, VERO_NETTOVARALL);

DROP taulu_&PVERO taulu_&PVERO_VARALL;

/* Valtionvero kattosäännön jälkeen */
%ValtVero_FinalS(VVKAT, VERO_VUOSI, YHTVALTVEROTULO, VALTTULOVERO, PAAOMAVERO3, SUM(KUNNALLISVERO5, SAIRAUSVAKUUTUSMAKSU5, KELAVAKUUTUSMAKSU5, KIRKOLLISVERO5));

VARVERKAT = MIN(VAVERO, VVKAT);

VALTTULVERKAT = SUM(VVKAT, -VARVERKAT);

VALTTULVERANSKAT = MIN(VALTTULVERKAT, VALTTULOANSVERO5);

/* Kaikki verot kattosäännön jälkeen */
KAIKKIVEROT1 = SUM(KUNNALLISVERO5, SAIRAUSVAKUUTUSMAKSU5, KELAVAKUUTUSMAKSU5, KIRKOLLISVERO5, VAVERO, VALTTULVERKAT);

IF VALTTULOVERO < TYOTULVAH THEN TEMPD = SUM(TYOTULVAH, -VALTTULOVERO);
ELSE TEMPD = 0;

IF VERO_VUOSI < 2009 THEN TEMPE = MIN(TEMPD, SUM(KUNNALLISVERO5, SAIRAUSVAKUUTUSMAKSU5, KELAVAKUUTUSMAKSU5, KIRKOLLISVERO5));
ELSE TEMPE = 0; 

/* Kaikki verot yhtiöveron hyvityksen ja valtionverotuksen ans.tuloväh. (ennen 2009) jälkeen */
KAIKKIVEROT2 = SUM(KUNNALLISVERO5, SAIRAUSVAKUUTUSMAKSU5, KELAVAKUUTUSMAKSU5, KIRKOLLISVERO5, VALTTULOANSVERO5, PAAOMAVERO3, -YHTHYVYHT, -TEMPE);

/* Yle-vero */
%YleVeroS(YLEVERO, VERO_VUOSI, INF, VERO_IKA, SUM(PUHDANSTULO, PUHDPOTULO), 0); 

/* Kaikki verot (ml. palkansaajan vakmaksut ja Yle-vero) */
KAIKKIVEROT3 = SUM(KAIKKIVEROT2, TYOELMAKSU, TYOTMAKSU, SPMAKSU, YLEVERO);

VEROJENOSUUS = KAIKKIVEROT3 / KOKONTULO * 100;
	
NETTOTULOT = SUM(KOKONTULO, -KAIKKIVEROT3);

%ValtTuloVeroS(TEMPF, VERO_VUOSI, INF, VALTVEROTULO, 0);

IF TEMPF < TYOTULVAH THEN TEMPG = SUM(TYOTULVAH, -TEMPF);
ELSE TEMPG = 0;

IF VERO_VUOSI < 2009 THEN TEMPH = TEMPG;
ELSE TEMPH = 0;

/* Veronsaajien osuudet */
%YhtHyvJakoS(VALTIO1, 1, YHTHYVANS, TEMPB, SUM(VALTTULOANSVERO3, PAAOMAVERO3), VALTTULOANSVERO5, KUNNALLISVERO5, SVMAKSU, 0, KIRKOLLISVERO5);
VALTIO = MAX(SUM(VALTIO1, -TEMPH), 0);

%YhtHyvJakoS(KUNNAT, 2, YHTHYVANS, TEMPB, SUM(VALTTULOANSVERO3, PAAOMAVERO3), VALTTULOANSVERO5, KUNNALLISVERO5, SVMAKSU, 0, KIRKOLLISVERO5);

%YhtHyvJakoS(KELA1, 3, YHTHYVANS, TEMPB, SUM(VALTTULOANSVERO3, PAAOMAVERO3), VALTTULOANSVERO5, KUNNALLISVERO5, SVMAKSU, 0, KIRKOLLISVERO5);
KELA = SUM(SAIRAUSVAKUUTUSMAKSU5, KELAVAKUUTUSMAKSU5, SPMAKSU);

%YhtHyvJakoS(KIRKKO, 5, YHTHYVANS, TEMPB, SUM(VALTTULOANSVERO3, PAAOMAVERO3), VALTTULOANSVERO5, KUNNALLISVERO5, SVMAKSU, 0, KIRKOLLISVERO5);

ELTTVAKLAIT = SUM(TYOELMAKSU, TYOTMAKSU);

VERONSYHT = SUM(VALTIO, KUNNAT, KELA, KIRKKO, ELTTVAKLAIT);

DROP taulu_&PVERO taulu_&PVERO_VARALL temp1 vahlapsia yliraja
 	alijenimm elvakmaksux TEMPA TEMPB TEMPC TEMPD TEMPE TEMPF TEMPG TEMPH 
 	VALTIO1 KELA1 PA MUUANS2 SPM SPMY 
	VVKAT VARVERKAT VALTTULVERKAT VALTTULVERANSKAT ELAKELISAVERO;;

/* Yritystulon ja osinkotulon jakaminen */ 

/* Yritystulon pääoma- ja ansiotulo-osuus */
%PomaOsuusS(YTPOT, VERO_VUOSI, INF, 1, VERO_VAIHT, VERO_YTULO, VERO_YRITVARALL, VERO_YPALKKA);
YTAT = MAX(SUM(VERO_YTULO, -YTPOT), 0);

/* Muusta kuin pörssiyhtiöstä saadun osingon ja siihen liittyvän yhtiöveron hyvityksen pääomatulo- ja ansiotulo-osuus (1993 - 2004) */
%PomaOsuusS(OPOT, VERO_VUOSI, INF, 2, 0, VERO_OTULO, VERO_YRITVARALL, 0);
OAT = MAX(SUM(VERO_OTULO, -OPOT), 0);
%PomaOsuusS(YVHYVPOT, VERO_VUOSI, INF, 3, 0, VERO_OTULO, VERO_YRITVARALL, 0);
%YhtHyvS(YVHY, VERO_VUOSI, INF, VERO_OTULO);
YVHYVAT = MAX(YVHY, 0);

/* Osinkojen jakaminen verottomiin tuloihin, pääomatuloihin ja ansiotuloihin (1993-) */
%OsinkojenJakoS(OVT, VERO_VUOSI, INF, VERO_OSPKORKO, 1, VERO_JULKOSINKO, VERO_EIJULKOSINKO, VERO_OSAKKARVO);
%OsinkojenJakoS(OPO, VERO_VUOSI, INF, VERO_OSPKORKO, 2, VERO_JULKOSINKO, VERO_EIJULKOSINKO, VERO_OSAKKARVO);
%OsinkojenJakoS(OSAT, VERO_VUOSI, INF, VERO_OSPKORKO, 3, VERO_JULKOSINKO, VERO_EIJULKOSINKO, VERO_OSAKKARVO);
OYHT = SUM(OVT, OPO, OSAT);

DROP YVHY OPOT OAT kuuknro kkuuk w y z;

/* 3.2.7 Veromalli jos VERO_PUOLISO = 1 */

%IF &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;
	IF VERO_PUOLISO = 1 THEN DO;

	* Johdettuja tulokäsitteitä ja vähennyksiä ym. (e/v);

	* Kokonaistulot;
	PKOKONTULO = SUM(VERO_PPTULO, VERO_PMERITULO, VERO_PPRAHATULO, VERO_PMTULO, VERO_PETULO, VERO_POPRAHA, VERO_POSANSTULO, VERO_PMUUANSTULO, VERO_POSINKOTULO, VERO_PVUOKRATULO, VERO_PKORKOTULO, VERO_PMUUPOTULO);

	* Ansiotulot (ilman yhtiöveron hyvitystä);
	PANSIOTULO = SUM(VERO_PPTULO, VERO_PMERITULO, VERO_PPRAHATULO, VERO_PMTULO, VERO_PETULO, VERO_POPRAHA, VERO_POSANSTULO, VERO_PMUUANSTULO);

	* Pääomatulot (ilman yhtiöveron hyvitystä);
	PPOTULO = SUM(VERO_POSINKOTULO, VERO_PVUOKRATULO, VERO_PKORKOTULO, VERO_PMUUPOTULO);

	PPUHDPOTULO = SUM(PPOTULO, -VERO_PPOVAHENN);

	%TulonHankKulutS(PTULHANKSUMS, VERO_VUOSI, INF, VERO_PPTULO, VERO_PTULONHANKKULUT, VERO_PAYMAKSUT, VERO_PTYOMATKAKULUT, VERO_PKUUKAUDET);
	%TulonHankKulutS(PTULHANKSUMSM, VERO_VUOSI, INF, VERO_PMERITULO, VERO_PTULONHANKKULUT, 0, 0, VERO_KUUKAUDET);

	%AsuntoVahennysS(PASUNTOVAH, VERO_VUOSI, INF, VERO_PKUUKAUDET, VERO_PVUOKRA);

	PPUHDASANSTULO = MAX(SUM(PANSIOTULO, -PTULHANKSUMS, -PTULHANKSUMSM, -PASUNTOVAH), 0);

	/* Vähennykset: */

	/* Ansiotulovähennykset */
	PMUAANS2 = MAX(SUM(PANSIOTULO, -VERO_PETULO), 0);
	%AnsVahS(PANS, VERO_VUOSI, INF, PPUHDASANSTULO, SUM(VERO_PPTULO, VERO_PMERITULO, VERO_PMTULO)); /* 2023-2024 */
	%KunnAnsVahS(PKUNNANS, VERO_VUOSI, INF, PPUHDASANSTULO, PMUAANS2, SUM(VERO_PPTULO, VERO_PMERITULO, VERO_PMTULO), SUM(VERO_PPTULO, VERO_PMERITULO), PKOKONTULO); /* -2022 */

	/* Eläketulovähennykset */
	%ElTulVahS(PELVAH, VERO_VUOSI, INF, VERO_PETULO, PPUHDASANSTULO); /* 2023- */
	%ValtElTulVahS(PELVAHV, VERO_VUOSI, INF, VERO_PETULO, PPUHDASANSTULO, PKOKONTULO); /* -2022 */
	%KunnElTulVahS(PELVELVAHK, VERO_VUOSI, INF, VERO_PUOLISO, 0, VERO_PETULO, PPUHDASANSTULO, PKOKONTULO); /* -2022 */

	/* Opintorahavähennykset */
	%OpRahVahS(POPRAHVAH, VERO_VUOSI, INF, VERO_POPRAHA, PPUHDASANSTULO); /* 2023- */
	%KunnOpRahVahS(POPRAHVAHK, VERO_VUOSI, INF, VERO_POPISK, VERO_POPRAHA, PANSIOTULO, PPUHDASANSTULO); /* -2022 */

	/* Merityötulovähennykset */
	%VerMeriVahS(PMERIVAH, VERO_VUOSI, INF, VERO_PMERITULO); /* 2023- */
	%ValtVerMeriVahS(PMERIVAHVAL, VERO_VUOSI, INF, VERO_PMERITULO); /* -2022 */
	%KunnVerMeriVahS(PMERIVAHKUN, VERO_VUOSI, INF, VERO_PMERITULO); /* -2022 */

	/* Invalidivähennykset (-2022) */
	%KunnVerInvVahS(PINVVAH_K, VERO_VUOSI, INF, VERO_PINVOIKEUS82, VERO_PINVPROS, PPUHDASANSTULO, VERO_PETULO);
	%ValtVerInvVahS(PINVVAH, VERO_VUOSI, INF, VERO_PINVPROS, VERO_PETULO);
		
	/* Sosiaalivakuutusmaksut */
	%TyoelMaksuS(PTYOELMAKSU, VERO_VUOSI, INF, VERO_PIKA, VERO_PPTULO);
	%TyotMaksuS(PTYOTMAKSU, VERO_VUOSI, INF, VERO_PIKA, VERO_PPTULO);
	%SvPrahaMaksuS(PSPM, VERO_VUOSI, INF, VERO_PIKA, SUM(VERO_PPTULO, VERO_PMERITULO));
	%SvPRahaMaksuYS(PSPMY, VERO_VUOSI, INF, VERO_PIKA, 1, VERO_POSINKOTULO);
	PSPMAKSU = SUM(PSPM, PSPMY);

	/* Perusvähennykset */
	IF VERO_VUOSI >= 2023 THEN DO;
	/* Verotettava tulo ennen ja jälkeen perusvähennyksen (2023-) */
		PVEROTULOP = MAX(SUM(PPUHDASANSTULO, -PTYOELMAKSU, -PTYOTMAKSU, -PSPMAKSU, -PANS, -PMERIVAH, -PELVAH, -POPRAHVAH, -VERO_PMUUVAH), 0);
		%PerVahS(PPERVAH, VERO_VUOSI, INF, PVEROTULOP);
		PVEROTULO = MAX(SUM(PVEROTULOP, -PPERVAH), 0);
		PKUNNVERTULOSP = PVEROTULO;
	END;
	ELSE DO;
	/* Verotettava tulo kunnallisverotuksessa ennen ja jälkeen perusvähennyksen (-2022) */
		%YhtHyvS(PYHTHYVPO, VERO_VUOSI, INF, VERO_POSINKOTULO);
		IF VERO_VUOSI < 1993 THEN PPA = SUM(PKOKONTULO, PYHTHYVPO, -PTULHANKSUMS, -PTULHANKSUMSM, -VERO_PPOVAHENN);
		ELSE PPA = PPUHDASANSTULO;

		PKUNNVEROTULO = MAX(SUM(PPA, -PTYOELMAKSU, -PTYOTMAKSU, -PSPMAKSU, -PKUNNANS, -PMERIVAHKUN, -PELVELVAHK, -POPRAHVAHK, -VERO_PMUUVAHKUNN, -PINVVAH_K), 0);

		IF PKUNNVEROTULO < 0 THEN PKUNNVEROTULO = 0;
		%KunnPerVahS(PPERVAH_K, VERO_VUOSI, INF, PKUNNVEROTULO);
		PKUNNVERTULOSP = MAX(SUM(PKUNNVEROTULO, -PPERVAH_K), 0);
	END;

	/* Vähennyksiä veroista: */

	/* Työtulovähennykset */
	%TyotVahS(PTYOTULVAH, VERO_VUOSI, INF, SUM(VERO_PPTULO, VERO_PMERITULO, VERO_PMTULO, VERO_POSANSTULO), PPUHDASANSTULO, VERO_PIKA, 0, VERO_LAPSIA);

	/* Valtionverotuksen työtulo- ja palkkavähennys (-1988) */
	%ValtTyoTuloVahS(PVALTTVAH, VERO_VUOSI, INF, PANSIOTULO, SUM(VERO_PPTULO, VERO_PMERITULO));

	/* Valtionverotuksen elatusvelvollisuusvähennys */
	%ValtVerElVelvVahS(PVELVVAHV, VERO_VUOSI, INF, VERO_PEVLAPSIA, VERO_PELMAKSUT);

	/* Alijäämähyvitys */
	%AlijHyvS(PALIJHYV, VERO_VUOSI, INF, 1, VERO_LAPSIA, SUM(PPOTULO, PYHTHYVPO), VERO_PPOVAHENN, 0, 0, 0, VERO_PPUOLALIJ);

	/* Erityinen alijäämähyvitys */
	%AlijHyvEritS(PALIJHYVERIT, VERO_VUOSI, INF, SUM(PPOTULO, PYHTHYVPO), VERO_PPOVAHENN, 0, 0, VERO_ELVAKMAKSU);

	/* Kotitalousvähennys */
	%KotiTalVahS(PKOTIVAH, VERO_VUOSI, INF, VERO_PKOTITMENO);

	/* Yhtiöveron hyvitys (-2004) */
	IF VERO_VUOSI > 1992 THEN DO;
		%YhtHyvS(PYHTHYVANS, VERO_VUOSI, INF, VERO_POSANSTULO);
	END;
	ELSE PYHTHYVANS = 0;
		
	PYHTHYVYHT = SUM(PYHTHYVANS, PYHTHYVPO);

	IF VERO_VUOSI < 1993 THEN DO;
		PTEMPA = PKOKONTULO; 
	   	PTEMPB = PYHTHYVPO;
	END;
	ELSE DO;
		PTEMPA = PANSIOTULO;
		PTEMPB = 0;
	END;

	/* Valtionverotuksessa verotettava ansiotulo */
	IF VERO_VUOSI >= 2023 THEN
		PVALTVEROTULO = PVEROTULO;
	ELSE
		PVALTVEROTULO = MAX(SUM(PTEMPA, PTEMPB, PYHTHYVANS, -PTULHANKSUMS, -PTULHANKSUMSM, -PMERIVAHVAL, -PTYOELMAKSU, -PTYOTMAKSU, -PSPMAKSU, - PELVAHV, -PVALTTVAH, -VERO_PMUUVAHVALT), 0);

	IF VERO_VUOSI < 1995 THEN PTEMPC = VERO_PKULKOROT;
	ELSE PTEMPC = 0;

	/* Verotettava pääomatulo */
	PVEROPOTULO = MAX(SUM(PPOTULO, PYHTHYVPO, -VERO_PASKOROT, VERO_PENSASKOROT, -VERO_PPOVAHENN, -PTEMPC), 0);
	/* Verotettava tulo valtionverotuksessa yhteensä */
	IF VERO_VUOSI >= 1993 THEN
		PYHTVALTVEROTULO = SUM(PVALTVEROTULO, PVEROPOTULO); /* 1993- */
	ELSE IF VERO_VUOSI <= 1992 THEN
		PYHTVALTVEROTULO = PVALTVEROTULO; /* -1992 */

	/* Tuloverot ennen työtulovähennystä */
	%ValtTuloVeroS(PVALTTULOVERO, VERO_VUOSI, INF, PVALTVEROTULO, 0);

	/* Eläketulon lisävero */
	IF VERO_VUOSI >= 2023 THEN DO;
		%ElakeLisaVeroS(PELAKELISAVERO, VERO_VUOSI, INF, VERO_PETULO, PELVAH);
	END; 
	ELSE DO;	
		%ElakeLisaVeroS(PELAKELISAVERO, VERO_VUOSI, INF, VERO_PETULO, PELVAHV);
	END;
		
	PVALTTULOVERO = SUM(PVALTTULOVERO, PELAKELISAVERO);

	/* Kunnallisvero*/
	%KunnVeroS(PKUNNVERO, VERO_VUOSI, INF, VERO_PKESKIM, VERO_PKUNNPROS, PKUNNVERTULOSP);

	/* Sairausvakuutusmaksu */
	%SairVakMaksuS(PSVMAKSU, VERO_VUOSI, INF, PKUNNVERTULOSP, VERO_PETULO, SUM(VERO_PPTULO, VERO_PMERITULO, VERO_PMTULO));

	/* Kansaneläkevakuutusmaksu */
	%KansElVakMaksuS(PKEVMAKSU, VERO_VUOSI, INF, PKUNNVERTULOSP, VERO_PETULO);

	/* Kirkollisvero */
	IF VERO_PKIRKOSSA = 1 THEN DO;
		%KirkVeroS(PKIRKVEROS, VERO_VUOSI, INF, VERO_PKESKIM, VERO_PKIRKPROS, PKUNNVERTULOSP);
	END;
	ELSE PKIRKVEROS = 0;

	/* Pääomatulon vero */
	%POTulonVeroEritS(PPOTULOVERO, VERO_VUOSI, INF, VERO_POSINKOTULO, SUM(VERO_PVUOKRATULO, VERO_PKORKOTULO, VERO_PMUUPOTULO), SUM(VERO_PPOVAHENN, VERO_PASKOROT, VERO_PENSASKOROT), VERO_PKULKOROT, VERO_PELVAKMAKSU);

	/* Tuloverot valtionverotuksen työtulovähennyksen jälkeen (jaetaan eri verolajeille, jos vuosi > 2008) */
	IF VERO_VUOSI > 2008 THEN DO;
		%VahennJakoS(PVALTTULOANSVERO, VERO_VUOSI, PTYOTULVAH, 1, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);
		%VahennJakoS(PKUNNALLISVERO, VERO_VUOSI, PTYOTULVAH, 2, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);
		%VahennJakoS(PSAIRAUSVAKUUTUSMAKSU, VERO_VUOSI, PTYOTULVAH, 3, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);
		%VahennJakoS(PKELAVAKUUTUSMAKSU, VERO_VUOSI, PTYOTULVAH, 4, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);
		%VahennJakoS(PKIRKOLLISVERO, VERO_VUOSI, PTYOTULVAH, 5, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);
	END;
	ELSE DO;
		PVALTTULOANSVERO = MAX(SUM(PVALTTULOVERO, -PTYOTULVAH), 0);
		PKUNNALLISVERO = PKUNNVERO;
		PSAIRAUSVAKUUTUSMAKSU = PSVMAKSU;
		PKELAVAKUUTUSMAKSU = PKEVMAKSU;
		PKIRKOLLISVERO = PKIRKVEROS;
	END;

	/* Tuloverot lapsivähennyksen jälkeen (2015-2017) */
	%ValtVerLapsVahS(PVALTLAPSVAH, VERO_VUOSI, INF,  0, VERO_LAPSIA, SUM(PPUHDASANSTULO, PPUHDPOTULO));

	IF VERO_VUOSI > 2014 THEN DO;
		%VahennJakoS(PVALTTULOANSVERO2, VERO_VUOSI, PVALTLAPSVAH, 1, PVALTTULOANSVERO, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);
		%VahennJakoS(PKUNNALLISVERO2, VERO_VUOSI, PVALTLAPSVAH, 2, PVALTTULOANSVERO, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);
		%VahennJakoS(PSAIRAUSVAKUUTUSMAKSU2, VERO_VUOSI, PVALTLAPSVAH, 3, PVALTTULOANSVERO, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);
		%VahennJakoS(PKELAVAKUUTUSMAKSU2, VERO_VUOSI, PVALTLAPSVAH, 4, PVALTTULOANSVERO, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);
		%VahennJakoS(PKIRKOLLISVERO2, VERO_VUOSI, PVALTLAPSVAH, 5, PVALTTULOANSVERO, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);
		%VahennJakoS(PPAAOMAVERO2, VERO_VUOSI, PVALTLAPSVAH, 6, PVALTTULOANSVERO, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);
	END;
	ELSE DO;
		PVALTTULOANSVERO2 = PVALTTULOANSVERO;
		PKUNNALLISVERO2 = PKUNNALLISVERO;
		PSAIRAUSVAKUUTUSMAKSU2 = PSAIRAUSVAKUUTUSMAKSU;
		PKELAVAKUUTUSMAKSU2 = PKELAVAKUUTUSMAKSU;
		PKIRKOLLISVERO2 = PKIRKOLLISVERO; 
		PPAAOMAVERO2 = PPOTULOVERO;
	END;

	/*  Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen */
	PVALTTULOINV = MAX(SUM(PVALTTULOANSVERO2, -PINVVAH, -PVELVVAHV), 0);

	/* Tuloverot kotitalousvähennyksen jälkeen */
	%VahennJakoS(PVALTTULOANSVERO3, VERO_VUOSI, PKOTIVAH, 1, PVALTTULOINV, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2, PPAAOMAVERO2);
	%VahennJakoS(PKUNNALLISVERO3, VERO_VUOSI, PKOTIVAH, 2, PVALTTULOINV, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2, PPAAOMAVERO2);
	%VahennJakoS(PSAIRAUSVAKUUTUSMAKSU3, VERO_VUOSI, PKOTIVAH, 3, PVALTTULOINV, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2, PPAAOMAVERO2);
	%VahennJakoS(PKELAVAKUUTUSMAKSU3, VERO_VUOSI, PKOTIVAH, 4, PVALTTULOINV, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2, PPAAOMAVERO2);
	%VahennJakoS(PKIRKOLLISVERO3, VERO_VUOSI, PKOTIVAH, 5, PVALTTULOINV, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2, PPAAOMAVERO2);
	%VahennJakoS(PPAAOMAVERO3, VERO_VUOSI, PKOTIVAH, 6, PVALTTULOINV, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2, PPAAOMAVERO2);

	/* Tuloverot alijäämähyvityksen jälkeen */
	%AlijHyvJakoS(PVALTTULOANSVERO4, VERO_VUOSI, 1, PALIJHYV, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, PKELAVAKUUTUSMAKSU3, PKIRKOLLISVERO3);
	%AlijHyvJakoS(PKUNNALLISVERO4, VERO_VUOSI, 2, PALIJHYV, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, PKELAVAKUUTUSMAKSU3, PKIRKOLLISVERO3);
	%AlijHyvJakoS(PSAIRAUSVAKUUTUSMAKSU4, VERO_VUOSI, 3, PALIJHYV, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, PKELAVAKUUTUSMAKSU3, PKIRKOLLISVERO3);
	%AlijHyvJakoS(PKELAVAKUUTUSMAKSU4, VERO_VUOSI, 4, PALIJHYV, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, PKELAVAKUUTUSMAKSU3, PKIRKOLLISVERO3);
	%AlijHyvJakoS(PKIRKOLLISVERO4, VERO_VUOSI, 5, PALIJHYV, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, PKELAVAKUUTUSMAKSU3, PKIRKOLLISVERO3);

	/* Tuloverot erityisen alijäämähyvityksen jälkeen */
	%VahennJakoS(PVALTTULOANSVERO5, VERO_VUOSI, PALIJHYVERIT, 1, PVALTTULOANSVERO4, PKUNNALLISVERO4, PSAIRAUSVAKUUTUSMAKSU4, 0, PKIRKOLLISVERO4, PVALTTULOANSVERO4);
	%VahennJakoS(PKUNNALLISVERO5, VERO_VUOSI, PALIJHYVERIT, 2, PVALTTULOANSVERO4, PKUNNALLISVERO4, PSAIRAUSVAKUUTUSMAKSU4, 0, PKIRKOLLISVERO4, PVALTTULOANSVERO4);
	%VahennJakoS(PSAIRAUSVAKUUTUSMAKSU5, VERO_VUOSI, PALIJHYVERIT, 3, PVALTTULOANSVERO4, PKUNNALLISVERO4, PSAIRAUSVAKUUTUSMAKSU4, 0, PKIRKOLLISVERO4, PVALTTULOANSVERO4);
	%VahennJakoS(PKELAVAKUUTUSMAKSU5, VERO_VUOSI, PALIJHYVERIT, 4, PVALTTULOANSVERO4, PKUNNALLISVERO4, PSAIRAUSVAKUUTUSMAKSU4, 0, PKIRKOLLISVERO4, PVALTTULOANSVERO4);
	%VahennJakoS(PKIRKOLLISVERO5, VERO_VUOSI, PALIJHYVERIT, 5, PVALTTULOANSVERO4, PKUNNALLISVERO4, PSAIRAUSVAKUUTUSMAKSU4, 0, PKIRKOLLISVERO4, PVALTTULOANSVERO4);

	/* Ansiotulojen verot yhteensä */
	PANSTULVEROT = SUM(PVALTTULOANSVERO5, PKUNNALLISVERO5, PSAIRAUSVAKUUTUSMAKSU5, PKELAVAKUUTUSMAKSU5, PKIRKOLLISVERO5);

	/* Varallisuusvero */
	%VarallVeroS(PVAVERO, VERO_VUOSI, INF, 1, VERO_LAPSIA, VERO_PVAKASU, VERO_PNETTOVARALL);

	DROP taulu_&PVERO taulu_&PVERO_VARALL;

	/* Valtionvero kattosäännön jälkeen */
	%ValtVero_FinalS(PVVKAT, VERO_VUOSI, PYHTVALTVEROTULO, PVALTTULOVERO, PPAAOMAVERO3, SUM(PKUNNALLISVERO5, PSAIRAUSVAKUUTUSMAKSU5, PKELAVAKUUTUSMAKSU5, PKIRKOLLISVERO5));

	PVARVERKAT = MIN(PVAVERO, PVVKAT);

	PVALTTULVERKAT = SUM(PVVKAT, -PVARVERKAT);

	PVALTTULVERANSKAT = MIN(PVALTTULVERKAT, PVALTTULOANSVERO5);

	/* Kaikki verot kattosäännön jälkeen */
	PKAIKKIVEROT1 = SUM(PKUNNALLISVERO5, PSAIRAUSVAKUUTUSMAKSU5, PKELAVAKUUTUSMAKSU5, PKIRKOLLISVERO5, PVAVERO, PVALTTULVERKAT);

	IF PVALTTULOVERO < PTYOTULVAH THEN PTEMPD = SUM(PTYOTULVAH, -PVALTTULOVERO);
	ELSE PTEMPD = 0;

	IF VERO_VUOSI < 2009 THEN PTEMPE = MIN(PTEMPD, SUM(PKUNNALLISVERO5, PSAIRAUSVAKUUTUSMAKSU5, PKELAVAKUUTUSMAKSU5, PKIRKOLLISVERO5));
	ELSE PTEMPE = 0; 

	/* Kaikki verot yhtiöveron hyvityksen ja valtionverotuksen ans.tuloväh. (ennen 2009) jälkeen */
	PKAIKKIVEROT2 = SUM(PKUNNALLISVERO5, PSAIRAUSVAKUUTUSMAKSU5, PKELAVAKUUTUSMAKSU5, PKIRKOLLISVERO5, PVALTTULOANSVERO5, PPAAOMAVERO3, -PYHTHYVYHT, -PTEMPE);

	/* Yle-vero */
	%YleVeroS(PYLEVERO, VERO_VUOSI, INF, VERO_PIKA, SUM(PPUHDASANSTULO, PPUHDPOTULO), 0); 

	/* Kaikki verot (ml. palkansaajan vakmaksut ja Yle-vero) */
	PKAIKKIVEROT3 = SUM(PKAIKKIVEROT2, PTYOELMAKSU, PTYOTMAKSU, PSPMAKSU, PYLEVERO);

	PVEROJENOSUUS = PKAIKKIVEROT3 / PKOKONTULO * 100; 

	PNETTOTULOT = SUM(PKOKONTULO, -PKAIKKIVEROT3);

	%ValtTuloVeroS(PTEMPF, VERO_VUOSI, INF, PVALTVEROTULO, 0);

	IF PTEMPF < PTYOTULVAH THEN PTEMPG = SUM(PTYOTULVAH, -PTEMPF);
	ELSE PTEMPG = 0;

	IF VERO_VUOSI < 2009 THEN PTEMPH = PTEMPG;
	ELSE PTEMPH = 0;

	/* Veronsaajien osuudet */
	%YhtHyvJakoS(PVALTIO1, 1, PYHTHYVANS, PTEMPB, SUM(PVALTTULOANSVERO3, PPAAOMAVERO3), PVALTTULOANSVERO5, PKUNNALLISVERO5, PSVMAKSU, 0, PKIRKOLLISVERO5);
	PVALTIO = SUM(PVALTIO1, -PTEMPH);

	%YhtHyvJakoS(PKUNNAT, 2, PYHTHYVANS, PTEMPB, SUM(PVALTTULOANSVERO3, PPAAOMAVERO3), PVALTTULOANSVERO5, PKUNNALLISVERO5, PSVMAKSU, 0, PKIRKOLLISVERO5);

	%YhtHyvJakoS(PKELA1, 3, PYHTHYVANS, PTEMPB, SUM(PVALTTULOANSVERO3, PPAAOMAVERO3), PVALTTULOANSVERO5, PKUNNALLISVERO5, PSVMAKSU, 0, PKIRKOLLISVERO5);
	PKELA = SUM(PKELA1, PSPMAKSU);

	%YhtHyvJakoS(PKIRKKO, 5, PYHTHYVANS, PTEMPB, SUM(PVALTTULOANSVERO3, PPAAOMAVERO3), PVALTTULOANSVERO5, PKUNNALLISVERO5, PSVMAKSU, 0, PKIRKOLLISVERO5);

	PELTTVAKLAIT = SUM(PTYOELMAKSU, PTYOTMAKSU);

	PVERONSYHT = SUM(PVALTIO, PKUNNAT, PKELA, PKIRKKO, PELTTVAKLAIT);

	/* Puolisot yhteensä */

	BRUTTOTULOT = SUM(KOKONTULO, PKOKONTULO);
	VEROTYHT = SUM(KAIKKIVEROT3, PKAIKKIVEROT3);
	VEROJENOSTUL = (VEROTYHT / BRUTTOTULOT) * 100;
	NETTULOT = SUM(BRUTTOTULOT, -VEROTYHT);

	DROP taulu_&PVERO taulu_&PVERO_VARALL temp1 elvakmaksux PTEMPA PTEMPB PTEMPC 
		PTEMPD PTEMPE PTEMPF PTEMPG PTEMPH PVALTIO1 PKELA1 PPA PSPM PSPMY PMUAANS2
		PVVKAT PVARVERKAT PVALTTULVERKAT PVALTTULVERANSKAT PELAKELISAVERO kuuknro kkuuk w y z;
END;
%END;

RUN;

%MEND Vero_Simuloi_Esimerkki;

%Vero_Simuloi_Esimerkki;


/* 3.3 Lasketaan marginaaliveroaste */

%MACRO Vero_Simuloi_MargVero;

/* 3.3.1 Otetaan talteen alkuperäiset tulokset ja nimetään 
         laskennassa tarvittava verotieto uudelleen */

DATA TEMP.VERO_ESIM_MARGVERO ;
SET OUTPUT.&TULOSNIMI_VE;
VEROT = KAIKKIVEROT3;
RUN;

/* 3.3.2 Simuloidaan veromalli uudestaan lisäämällä palkkatuloihin askeleen mukainen palkanlisä */

%Generoi_Muuttujat;

DATA OUTPUT.&TULOSNIMI_VE;
SET OUTPUT.&TULOSNIMI_VE;
VERO_PTULO = SUM(VERO_PTULO, VERO_ASKEL);
RUN;

%Vero_Simuloi_Esimerkki;

/* 3.3.3 Otetaan talteen uudelleen simuloidut tulokset ja nimetään 
         laskennassa tarvittava verotieto uudelleen */

DATA OUTPUT.&TULOSNIMI_VE;
SET OUTPUT.&TULOSNIMI_VE;
VEROT2 = KAIKKIVEROT3;
KEEP VEROT2;
RUN;

/* 3.3.4 Lasketaan marginaaliveroaste ja efektiivinen marginaaliveroaste */

DATA OUTPUT.&TULOSNIMI_VE;
MERGE OUTPUT.&TULOSNIMI_VE  TEMP.VERO_ESIM_MARGVERO ;
MARGIVERO = 100 * (SUM(VEROT2, -VEROT) / VERO_ASKEL);

DROP VEROT VEROT2;

/* 3.4 Määritellään muuttujille selkokieliset selitteet */

LABEL 
VERO_VUOSI = 'Lainsäädäntövuosi'
VERO_PTULO = 'Palkkatulo, (e/v)'
VERO_MERITULO = 'Merityötulo, (e/v)'
VERO_MTULO = 'Muu työtulo kuin palkkatulo, (e/v)'
VERO_PRAHATULO = 'Päivärahatulo, (e/v)'
VERO_ETULO = 'Eläketulo, (e/v)'
VERO_OPRAHA = 'Opintoraha, (e/v)'
VERO_OSANSTULO = 'Osinkotulo ansiotulona, (e/v)' 
VERO_MUUANSTULO = 'Muu ansiotulo, (e/v)'
VERO_OSINKOTULO = 'Osinkotulo pääomatulona, (e/v)'
VERO_VUOKRATULO = 'Vuokratulot vakituisesta asunnosta, (e/v)'
VERO_KORKOTULO = 'Veronalaiset korkotulot, (e/v)'
VERO_MUUPOTULO = 'Muu pääomatulo, (e/v)'
VERO_NETTOPALKKA = 'Nettopalkka, (e/kk)'
VERO_ASKEL = 'Tuloaskel, jolla tuloa korotetaan marginaaliveroastetta laskettaessa, (e/v)'
VERO_VAKASU = 'Vakituinen asunto varallisuuden osana, (0/1)'
VERO_NETTOVARALL = 'Nettovarallisuus, (e)'

VERO_TULONHANKKULUT = 'Tulonhankkimiskulut, (e/v)' 
VERO_AYMAKSUT = 'Ay-jäsenmaksut, (e/v)' 
VERO_TYOMATKAKULUT = 'Työmatkakulut, (e/v)' 
VERO_KUUKAUDET = 'Työasuntovähennykseen oikeuttavat kuukaudet' 
VERO_VUOKRA = 'Työasuntovähennykseen oikeuttava vuokra, (e/kk)' 
VERO_ELMAKSUT = 'Elatusmaksut, (e/v)'
VERO_POVAHENN = 'Pääomatulon hankkimisesta aiheuttavat menot, (e/v)'  
VERO_ASKOROT = 'Asunto- ja opintolainan korot, (e/v)'
VERO_ENSASKOROT = 'Ensiasuntoon kohdistuvan luoton korot, (e/v)'
VERO_KULKOROT = 'Kulutusluoton korot, (e/v)'
VERO_ELVAKMAKSU = 'Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-), (e/v)'
VERO_SAIRKULUT = 'Sairauskulut, (e/v)'
VERO_KOTITMENO = 'Kotitalousvähennykseen oikeuttavat menot, (e/v)'
VERO_MUUVAH = 'Muita vähennyksiä tulosta verotuksessa, (e/v) (vuodesta 2023 alkaen)'
VERO_MUUVAHVALT = 'Muita vähennyksiä tulosta valtionverotuksessa, (e/v)'
VERO_MUUVAHKUNN = 'Muita vähennyksiä tulosta kunnallisverotuksessa, (e/v)'

VERO_PUOLISO = 'Onko puolisoa, (0/1)'
VERO_IKA = 'Ikä'
VERO_LAPSIA = 'Huollettavina olevien alaikäisten lasten lkm'
VERO_EVLAPSIA = 'Elatusvellvollisten lasten lkm'
VERO_OPISK = 'Onko opiskelija, (0/1)'
VERO_YRIT = 'Onko yrittäjä, (0/1)'
VERO_INVPROS = 'Vamman haitta-aste (1-100)'
VERO_INVOIKEUS82 = 'Oikeus invalidivähennykseen eläketulosta vuonna 1982 (1 = tosi, 0 = epätosi)'
VERO_TYOTKUUK = 'Työttömyyskuukaudet, (kk)'
VERO_PUOLALIJ = 'Puolison alijäämähyvitys, (e/v)'
VERO_KUNNPROS = 'Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo), (%)'
VERO_KIRKPROS = 'Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo), (%)'
VERO_KESKIM = 'Käytetäänkö keskimääräistä kunnallis-, ja kirkollisveroprosenttia, (0/1)'
VERO_KIRKOSSA = 'Kuuluuko kirkkoon, (0/1)'

VERO_VAIHT = 'Yritystulon ja osinkotulon jakaminen (1993-): Vaihtoehtoinen alempi osuus, (0/1)'
VERO_YTULO = 'Yritystulon ja osinkotulon jakaminen (1993-): Jaettava yritystulo, (e/v)'
VERO_YRITVARALL = 'Yritystulon ja osinkotulon jakaminen (1993-): Yritysvarallisuus/Osakkeiden arvo, (e)'
VERO_YPALKKA = 'Yritystulon ja osinkotulon jakaminen (1993-): Yrityksessä maksetut palkat, (e/v)'
VERO_OTULO = 'Yritystulon ja osinkotulon jakaminen (1993-): Osinkotulo, (e/v)'
VERO_OSPKORKO = 'Yritystulon ja osinkotulon jakaminen (1993-): Osuuspääoman korkoa? (0/1)'
VERO_JULKOSINKO = 'Yritystulon ja osinkotulon jakaminen (1993-): Osinko julk.not yhtiöstä, (e/v)'
VERO_EIJULKOSINKO = 'Yritystulon ja osinkotulon jakaminen (1993-): Muu osinko, (e/v)'
VERO_OSAKKARVO = 'Yritystulon ja osinkotulon jakaminen (1993-): Muiden osakkeiden matemaattinen arvo, (e)'

TULOVERO = 'Yksinkertainen malli: Tulovero, (e)'
BRUTTOTULO = 'Yksinkertainen malli: Nettokuukausitulosta johdettu bruttotulo, (e)'
MARGINAALIVEROASTE = 'Yksinkertainen malli: Marginaaliveroaste, (%)'
TULOVERO_ELAKE = 'Yksinkertainen malli: Eläketulon verot, (e)'
TULOVERO_PRAHA = 'Yksinkertainen malli: Tuloverot kun tulot ovat työttömyysturvaa tai muuta vastaavaa sosiaalietuutta, (e)'
VOSUUSPTULO = 'Yksinkertainen malli: Verojen osuus palkkatuloista, (%)'
VOSUUSNKTULO = 'Verojen osuus - Käänteisfunktio: nettokuukausituloa vastaava bruttokuukausitulo, (%)'
VOSUUSETULO = 'Yksinkertainen malli: Verojen osuus eläketulosta, (%)'
VOSUUSPRAHATULO = 'Yksinkertainen malli: Verojen osuus päivärahatulosta, (%)'

KOKONTULO = 'Kokonaistulot, (e)'
ANSIOTULO = 'Ansiotulot (ilman yhtiöveron hyvitystä), (e)'
POTULO = 'Pääomatulot (ilman yhtiöveron hyvitystä), (e)'
PUHDPOTULO = 'Puhdas pääomatulo, (e)'
TULHANKSUMS = 'Tulonhankkimiskulut (ml. tulonhankkimisvähennys, ay-maksut, työmatkakulut), (e)'
TULHANKSUMSM = 'Tulonhankkimiskulut merityötuloista (ml. tulonhankkimisvähennys), (e)'
ASUNTOVAH = 'Työasuntovähennys, (e)'
PUHDANSTULO = 'Puhdas ansiotulo, (e)'
ELVAH = 'Eläketulovähennys (2023-), (e)'
MERIVAH = 'Merityötulovähennys (2023-), (e)'
ANS = 'Ansiotulovähennys (2023-2024), (e)'
OPRAHVAH = 'Opintorahavähennys (2023-), (e)'
ELVAHV = 'Valtionverotuksen eläketulovähennys (-2022), (e)'
MERIVAHVAL = 'Valtionverotuksen merityötulovähennys (-2022), (e)'
VALTTVAH = 'Valtionverotuksen työtulovähennys ja palkkavähennys (-1988), (e)'
KUNNANS = 'Kunnallisverotuksen ansiotulovähennys (-2022), (e)'
ELVELVAHK = 'Kunnallisverotuksen eläketulovähennys (-2022), (e)'
MERIVAHKUN = 'Kunnallisverotuksen merityötulovähennys (-2022), (e)'
OPRAHVAHK = 'Kunnallisverotuksen opintorahavähennys (-2022), (e)'
TYOELMAKSU = 'Työntekijän eläkevakuutusmaksu, (e)'
TYOTMAKSU = 'Työntekijän työttömyysvakuutusmaksu, (e)'
SPMAKSU = 'Sairausvakuutuksen päivärahamaksu, (e)'
KUNNVEROTULO = 'Verotettava tulo kunnallisverotuksessa ennen perusvähennystä (-2022), (e)'
PERVAH_K = 'Kunnallisverotuksen perusvähennys (-2022), (e)'
KUNNVERTULOSP = 'Verotettava tulo kunnallisverotuksessa, (e)'
VEROTULOP = 'Verotettava tulo ennen perusvähennystä (2023-)'
PERVAH = 'Perusvähennys (2023-), (e)'
VEROTULO = 'Verotettava tulo perusvähennyksen jälkeen (2023-)'
TYOTULVAH = 'Työtulovähennys (ent. valtionverotuksen ansiotulovähennys), (e)'
INVVAH = 'Invalidivähennys valtionverosta (ja vanhuusvähennys) (-2022), (e)' 
INVVAH_K = 'Invalidivähennys kunnallisverosta (-2022), (e)' 
VELVVAHV = 'Elatusvelvollisuusvähennys valtion verosta, (e)'
ALIJHYV = 'Alijäämähyvitys yhteensä, (e)'
ALIJHYVERIT = 'Erityinen alijäämähyvitys, (e)'
KOTIVAH = 'Kotitalousvähennys, (e)'
YHTHYVANS = 'Yhtiöveron hyvitys ansiotulona (ansiotulo-osingosta), (e)'
YHTHYVPO = 'Yhtiöveron hyvitys pääomatulona (pääomatulo-osingosta), (e)'
YHTHYVYHT = 'Yhtiöveron hyvitys, (e)'
VALTVEROTULO = 'Valtionverotuksessa verotettava tulo (-1992) tai ansiotulo (1993-), (e)'
VEROPOTULO = 'Verotettava pääomatulo (1993-), (e)'
YHTVALTVEROTULO = 'Verotettava tulo valtionverotuksessa yhteensä, (e)'

VALTTULOVERO = 'Valtion tulovero (-1992) tai ansiotulojen valtionvero (1993-), (e)'
KUNNVERO = 'Kunnallisvero, (e)'
SVMAKSU = 'Sairausvakuutusmaksu/sairaanhoitomaksu, (e)'
KEVMAKSU = 'Kansaneläkevakuutusmaksu, (e)'
KIRKVEROS = 'Kirkollisvero, (e)'
POTULOVERO = 'Pääomatulon vero, (e)'
VALTLAPSVAH = 'Lapsivähennys, (e)'

VALTTULOANSVERO = 'Ansiotulojen valtionvero työtulovähennyksen jälkeen, (e)'
KUNNALLISVERO = 'Kunnallisvero työtulovähennyksen jälkeen, (e)'
SAIRAUSVAKUUTUSMAKSU = 'Sairausvakuutusmaksu työtulovähennyksen jälkeen, (e)'
KELAVAKUUTUSMAKSU = 'Kansaneläkevakuutusmaksu työtulovähennyksen jälkeen, (e)'
KIRKOLLISVERO = 'Kirkollisvero työtulovähennyksen jälkeen, (e)'

VALTTULOINV = 'Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen, (e)'

VALTTULOANSVERO2 = 'Ansiotulojen valtionvero lapsivähennyksen jälkeen, (e)'
KUNNALLISVERO2 = 'Kunnallisvero lapsivähennyksen jälkeen, (e)'
SAIRAUSVAKUUTUSMAKSU2 = 'Sairausvakuutusmaksu lapsivähennyksen jälkeen, (e)'
KELAVAKUUTUSMAKSU2 = 'Kansaneläkevakuutusmaksu lapsivähennyksen jälkeen, (e)'
KIRKOLLISVERO2 = 'Kirkollisvero lapsivähennyksen jälkeen, (e)'
PAAOMAVERO2 = 'Pääomatulon vero lapsivähennyksen jälkeen, (e)'

VALTTULOANSVERO3 = 'Ansiotulojen valtionvero kotitalousvähennyksen jälkeen, (e)'
KUNNALLISVERO3 = 'Kunnallisvero kotitalousvähennyksen jälkeen, (e)'
SAIRAUSVAKUUTUSMAKSU3 = 'Sairausvakuutusmaksu kotitalousvähennyksen jälkeen, (e)'
KELAVAKUUTUSMAKSU3 = 'Kansaneläkevakuutusmaksu kotitalousvähennyksen jälkeen, (e)'
KIRKOLLISVERO3 = 'Kirkollisvero kotitalousvähennyksen jälkeen, (e)'
PAAOMAVERO3 = 'Pääomatulon vero kotitalousvähennyksen jälkeen, (e)'

VALTTULOANSVERO4 = 'Ansiotulojen valtionvero alijäämähyvityksen jälkeen, (e)'
KUNNALLISVERO4 = 'Kunnallisvero alijäämähyvityksen jälkeen, (e)'
SAIRAUSVAKUUTUSMAKSU4 = 'Sairausvakuutusmaksu alijäämähyvityksen jälkeen, (e)'
KELAVAKUUTUSMAKSU4 = 'Kansaneläkevakuutusmaksu alijäämähyvityksen jälkeen, (e)'
KIRKOLLISVERO4 = 'Kirkollisvero alijäämähyvityksen jälkeen, (e)'

VALTTULOANSVERO5 = 'Ansiotulojen valtionvero erityisen alijäämähyvityksen jälkeen, (e)'
KUNNALLISVERO5 = 'Kunnallisvero erityisen alijäämähyvityksen jälkeen, (e)'
SAIRAUSVAKUUTUSMAKSU5 = 'Sairausvakuutusmaksu erityisen alijäämähyvityksen jälkeen, (e)'
KELAVAKUUTUSMAKSU5 = 'Kansaneläkevakuutusmaksu erityisen alijäämähyvityksen jälkeen, (e)'
KIRKOLLISVERO5 = 'Kirkollisvero erityisen alijäämähyvityksen jälkeen, (e)'

ANSTULVEROT = 'Ansiotulojen verot (1993-) tai tuloverot yhteensä, (e)'
VAVERO = 'Varallisuusvero (1993-2005), (e)'
KAIKKIVEROT1 = 'Kaikki verot kattosäännön jälkeen, (e)'
KAIKKIVEROT2 = 'Verot yhtiöveron hyvityksen ja valtionverotuksen ans.tuloväh. (ennen 2009) jälkeen, (e)'
YLEVERO = 'Yle-vero (2013-), (e)'
KAIKKIVEROT3 = 'Kaikki verot (ml. palkansaajan vakmaksut ja Yle-vero), (e)'
VEROJENOSUUS = 'Verojen osuus tuloista, (%)'
NETTOTULOT = 'Nettotulo, (e)'

VALTIO = 'Veronsaajien osuudet: Valtio, (e)'
KUNNAT = 'Veronsaajien osuudet: Kunnat, (e)'
KELA = 'Veronsaajien osuudet: KELA, (e)'
KIRKKO = 'Veronsaajien osuudet: Kirkko, (e)'
ELTTVAKLAIT = 'Veronsaajien osuudet: Eläke- ja työttömyysvakuutuslaitokset, (e)'
VERONSYHT = 'Veronsaajien osuudet yhteensä, (e)'

YTPOT = 'Yritystulosta pääomatulo, (e)'
YTAT = 'Yritystulosta ansiotuloa, (e)'
YVHYVPOT = 'Yhtiöveron hyvityksestä pääomatuloa, (e)'
YVHYVAT = 'Yhtiöveron hyvityksestä ansiotuloa, (e)'
OVT = 'Osingoista verotonta tuloa, (e)'
OPO = 'Osingoista pääomatuloa, (e)'
OSAT = 'Osingoista ansiotuloa, (e)'
OYHT = 'Osingot yhteensä, (e)'

MARGIVERO = 'Marginaaliveroaste, (%)'

/* 3.4 Määritellään puolison muuttujille selkokieliset selitteet (jos VERO_PUOLISO = 1) */

%IF &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

VERO_PPTULO = 'Puoliso: Palkkatulo, (e/v)'
VERO_PMERITULO = 'Puoliso: Merityötulo, (e/v)'
VERO_PMTULO = 'Puoliso: Muu työtulo kuin palkkatulo, (e/v)'
VERO_PPRAHATULO = 'Puoliso: Päivärahatulo, (e/v)'
VERO_PETULO = 'Puoliso: Eläketulo, (e/v)'
VERO_POPRAHA = 'Puoliso: Opintoraha, (e/v)'
VERO_POSANSTULO = 'Puoliso: Osinkotulo ansiotulona, (e/v)' 
VERO_PMUUANSTULO = 'Puoliso: Muu ansiotulo, (e/v)'
VERO_POSINKOTULO = 'Puoliso: Osinkotulo pääomatulona, (e/v)'
VERO_PVUOKRATULO = 'Puoliso: Vuokratulot vakituisesta asunnosta, (e/v)'
VERO_PKORKOTULO = 'Puoliso: Veronalaiset korkotulot, (e/v)'
VERO_PMUUPOTULO = 'Puoliso: Muu pääomatulo, (e/v)'
VERO_PVAKASU = 'Puoliso: Vakituinen asunto varallisuuden osana, (0/1)'
VERO_PNETTOVARALL = 'Puoliso: Nettovarallisuus, (e)'

VERO_PTULONHANKKULUT = 'Puoliso: Tulonhankkimiskulut, (e/v)' 
VERO_PAYMAKSUT = 'Puoliso: Ay-jäsenmaksut, (e/v)' 
VERO_PTYOMATKAKULUT = 'Puoliso: Työmatkakulut, (e/v)' 
VERO_PKUUKAUDET = 'Puoliso: Työasuntovähennykseen oikeuttavat kuukaudet (kk)' 
VERO_PVUOKRA = 'Puoliso: Työasuntovähennykseen oikeuttava vuokra, (e/kk)' 
VERO_PELMAKSUT = 'Puoliso: Elatusmaksut, (e/v)'
VERO_PPOVAHENN = 'Puoliso: Pääomatulon hankkimisesta aiheuttavat menot, (e/v)'  
VERO_PASKOROT = 'Puoliso: Asunto- ja opintolainan korot, (e/v)'
VERO_PENSASKOROT = 'Puoliso: Ensiasuntoon kohdistuvan luoton korot, (e/v)'
VERO_PKULKOROT = 'Puoliso: Kulutusluoton korot, (e/v)'
VERO_PELVAKMAKSU = 'Puoliso: Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-), (e/v)'
VERO_PKOTITMENO = 'Puoliso: Kotitalousvähennykseen oikeuttavat menot, (e/v)'
VERO_PMUUVAHVALT = 'Puoliso: Muita vähennyksiä tulosta valtionverotuksessa, (e/v)'
VERO_PMUUVAHKUNN = 'Puoliso: Muita vähennyksiä tulosta kunnallisverotuksessa, (e/v)'

VERO_PIKA = 'Puoliso: Ikä'
VERO_PEVLAPSIA = 'Puoliso: Elatusvellvollisten lasten lkm'
VERO_POPISK = 'Puoliso: Onko opiskelija, (0/1)'
VERO_PYRIT = 'Puoliso: Onko yrittäjä, (0/1)'
VERO_PINVPROS = 'Puoliso: Vamman haitta-aste (1-100)'
VERO_PINVOIKEUS82 = 'Puoliso: Oikeus invalidivähennykseen eläketulosta vuonna 1982 (1 = tosi, 0 = epätosi)' 
VERO_PTYOTKUUK = 'Puoliso: Työttömyyskuukaudet, (kk)'
VERO_PPUOLALIJ = 'Puoliso: Puolison alijäämähyvitys, (e/v)'
VERO_PKUNNPROS = 'Puoliso: Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo), (%)'
VERO_PKIRKPROS = 'Puoliso: Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo), (%)'
VERO_PKESKIM = 'Puoliso: Käytetäänkö keskimääräistä kunnallis-, ja kirkollisveroprosenttia, (0/1)'
VERO_PKIRKOSSA = 'Puoliso: Kuuluuko kirkkoon, (0/1)'

PKOKONTULO = 'Puoliso: Kokonaistulot, (e)'
PANSIOTULO = 'Puoliso: Ansiotulot (ilman yhtiöveron hyvitystä), (e)'
PPOTULO = 'Puoliso: Pääomatulot (ilma yhtiöveron hyvitystä), (e)'
PPUHDPOTULO = 'Puoliso: Puhdas pääomatulo, (e)'
PTULHANKSUMS = 'Puoliso: Tulonhankkimiskulut (ml. tulonhankkimisvähennys, ay-maksut, työmatkakulut), (e)'
PTULHANKSUMSM = 'Puoliso: Tulonhankkimiskulut merityötuloista (ml. tulonhankkimisvähennys), (e)'
PASUNTOVAH = 'Puoliso: Työasuntovähennys, (e)'
PPUHDASANSTULO = 'Puoliso: Puhdas ansiotulo, (e)'
PELVAH = 'Puoliso: Verotuksen eläketulovähennys (2023-), (e)'
PMERIVAH = 'Puoliso: Verotuksen merityötulovähennys (2023-), (e)'
POPRAHVAH = 'Puoliso: Verotuksen opintorahavähennys (2023-), (e)'
PANS = 'Puoliso: Verotuksen ansiotulovähennys (2023-2024), (e)'
PELVAHV = 'Puoliso: Valtionverotuksen eläketulovähennys (-2022), (e)'
PMERIVAHVAL = 'Puoliso: Valtionverotuksen merityötulovähennys (-2022), (e)'
PVALTTVAH = 'Puoliso: Valtionverotuksen työtulovähennys ja palkkavähennys (-1988), (e)'
PKUNNANS = 'Puoliso: Kunnallisverotuksen ansiotulovähennys (-2022), (e)'
PELVELVAHK = 'Puoliso: Kunnallisverotuksen eläketulovähennys (-2022), (e)'
PMERIVAHKUN = 'Puoliso: Kunnallisverotuksen merityötulovähennys (-2022), (e)'
POPRAHVAHK = 'Puoliso: Kunnallisverotuksen opintorahavähennys (-2022), (e)'
PTYOELMAKSU = 'Puoliso: Työntekijän eläkevakuutusmaksu, (e)'
PTYOTMAKSU = 'Puoliso: Työntekijän työttömyysvakuutusmaksu, (e)'
PSPMAKSU = 'Puoliso: Sairausvakuutuksen päivärahamaksu, (e)'
PKUNNVEROTULO = 'Puoliso: Verotettava tulo kunnallisverotuksessa ennen perusvähennystä (-2022), (e)'
PPERVAH_K = 'Puoliso: Kunnallisverotuksen perusvähennys (-2022), (e)'
PKUNNVERTULOSP = 'Puoliso: Verotettava tulo kunnallisverotuksessa, (e)'
PVEROTULOP = 'Puoliso: Verotettava tulo ennen perusvähennystä (2023-)'
PPERVAH = 'Puoliso: Perusvähennys (2023-), (e)'
PVEROTULO = 'Puoliso: Verotettava tulo perusvähennyksen jälkeen (2023-)'
PTYOTULVAH = 'Puoliso: Työtulovähennys (ent. valtionverotuksen ansiotulovähennys), (e)'
PINVVAH = 'Puoliso: Invalidivähennys valtionverosta (ja vanhuusvähennys) (-2022), (e)' 
PINVVAH_K = 'Puoliso: Invalidivähennys kunnallisverosta (-2022), (e)'
PVELVVAHV = 'Puoliso: Elatusvelvollisuusvähennys valtion verosta, (e)'
PALIJHYV = 'Puoliso: Alijäämähyvitys yhteensä, (e)'
PALIJHYVERIT = 'Puoliso: Erityinen alijäämähyvitys, (e)'
PKOTIVAH = 'Puoliso: Kotitalousvähennys, (e)'
PYHTHYVANS = 'Puoliso: Yhtiöveron hyvitys ansiotulona (ansiotulo-osingosta), (e)'
PYHTHYVPO = 'Puoliso: Yhtiöveron hyvitys pääomatulona (pääomatulo-osingosta), (e)'
PYHTHYVYHT = 'Puoliso: Yhtiöveron hyvitys, (e)'
PVALTVEROTULO = 'Puoliso: Valtionverotuksessa verotettava tulo (-1992) tai ansiotulo (1993-), (e)'
PVEROPOTULO = 'Puoliso: Verotettava pääomatulo (1993-), (e)'
PYHTVALTVEROTULO = 'Puoliso: Verotettava tulo valtionverotuksessa yhteensä, (e)'

PVALTTULOVERO = 'Puoliso: Valtion tulovero (-1992) tai ansiotulojen valtionvero (1993-), (e)'
PKUNNVERO = 'Puoliso: Kunnallisvero, (e)'
PSVMAKSU = 'Puoliso: Sairausvakuutusmaksu/sairaanhoitomaksu, (e)'
PKEVMAKSU = 'Puoliso: Kansaneläkevakuutusmaksu , (e)'
PKIRKVEROS = 'Puoliso: Kirkollisvero, (e)'
PPOTULOVERO = 'Puoliso: Pääomatulon vero, (e)'
PVALTLAPSVAH = 'Puoliso: Lapsivähennys, (e)'

PVALTTULOANSVERO = 'Puoliso: Ansiotulojen valtionvero työtulovähennyksen jälkeen, (e)'
PKUNNALLISVERO = 'Puoliso: Kunnallisvero työtulovähennyksen jälkeen, (e)'
PSAIRAUSVAKUUTUSMAKSU = 'Puoliso: Sairausvakuutusmaksu työtulovähennyksen jälkeen, (e)'
PKELAVAKUUTUSMAKSU = 'Puoliso: Kansaneläkevakuutusmaksu työtulovähennyksen jälkeen, (e)'
PKIRKOLLISVERO = 'Puoliso: Kirkollisvero työtulovähennyksen jälkeen, (e)'

PVALTTULOINV = 'Puoliso: Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen, (e)'

PVALTTULOANSVERO2 = 'Puoliso: Ansiotulojen valtionvero lapsivähennyksen jälkeen, (e)'
PKUNNALLISVERO2 = 'Puoliso: Kunnallisvero lapsivähennyksen jälkeen, (e)'
PSAIRAUSVAKUUTUSMAKSU2 = 'Puoliso: Sairausvakuutusmaksu lapsivähennyksen jälkeen, (e)'
PKELAVAKUUTUSMAKSU2 = 'Puoliso: Kansaneläkevakuutusmaksu lapsivähennyksen jälkeen, (e)'
PKIRKOLLISVERO2 = 'Puoliso: Kirkollisvero lapsivähennyksen jälkeen, (e)'
PPAAOMAVERO2 = 'Puoliso: Pääomatulon vero lapsivähennyksen jälkeen, (e)'

PVALTTULOANSVERO3 = 'Puoliso: Ansiotulojen valtionvero kotitalousvähennyksen jälkeen, (e)'
PKUNNALLISVERO3 = 'Puoliso: Kunnallisvero kotitalousvähennyksen jälkeen, (e)'
PSAIRAUSVAKUUTUSMAKSU3 = 'Puoliso: Sairausvakuutusmaksu kotitalousvähennyksen jälkeen, (e)'
PKELAVAKUUTUSMAKSU3 = 'Puoliso: Kansaneläkevakuutusmaksu kotitalousvähennyksen jälkeen, (e)'
PKIRKOLLISVERO3 = 'Puoliso: Kirkollisvero kotitalousvähennyksen jälkeen, (e)'
PPAAOMAVERO3 = 'Puoliso: Pääomatulon vero kotitalousvähennyksen jälkeen, (e)'

PVALTTULOANSVERO4 = 'Puoliso: Ansiotulojen valtionvero alijäämähyvityksen jälkeen, (e)'
PKUNNALLISVERO4 = 'Puoliso: Kunnallisvero alijäämähyvityksen jälkeen, (e)'
PSAIRAUSVAKUUTUSMAKSU4 = 'Puoliso: Sairausvakuutusmaksu alijäämähyvityksen jälkeen, (e)'
PKELAVAKUUTUSMAKSU4 = 'Puoliso: Kansaneläkevakuutusmaksu alijäämähyvityksen jälkeen, (e)'
PKIRKOLLISVERO4 = 'Puoliso: Kirkollisvero alijäämähyvityksen jälkeen, (e)'

PVALTTULOANSVERO5 = 'Puoliso: Ansiotulojen valtionvero erityisen alijäämähyvityksen jälkeen, (e)'
PKUNNALLISVERO5 = 'Puoliso: Kunnallisvero erityisen alijäämähyvityksen jälkeen, (e)'
PSAIRAUSVAKUUTUSMAKSU5 = 'Puoliso: Sairausvakuutusmaksu erityisen alijäämähyvityksen jälkeen, (e)'
PKELAVAKUUTUSMAKSU5 = 'Puoliso: Kansaneläkevakuutusmaksu erityisen alijäämähyvityksen jälkeen, (e)'
PKIRKOLLISVERO5 = 'Puoliso: Kirkollisvero erityisen alijäämähyvityksen jälkeen, (e)'

PANSTULVEROT = 'Puoliso: Ansiotulojen verot (1993-) tai tuloverot yhteensä, (e)'
PVAVERO = 'Puoliso: Varallisuusvero (1993-2005), (e)'
PKAIKKIVEROT1 = 'Puoliso: Kaikki verot kattosäännön jälkeen, (e)'
PKAIKKIVEROT2 = 'Puoliso: Verot yhtiöveron hyvityksen ja valtionverotuksen ans.tuloväh. (ennen 2009) jälkeen, (e)'
PYLEVERO = 'Puoliso: Yle-vero (2013-), (e)'
PKAIKKIVEROT3 = 'Puoliso: Kaikki verot (ml. palkansaajan vakmaksut ja Yle-vero), (e)'
PVEROJENOSUUS = 'Puoliso: Verojen osuus tuloista, (%)'
PNETTOTULOT = 'Puoliso: Nettotulo, (e)'

PVALTIO = 'Puoliso: Veronsaajien osuudet: Valtio, (e)'
PKUNNAT = 'Puoliso: Veronsaajien osuudet: Kunnat, (e)'
PKELA = 'Puoliso: Veronsaajien osuudet: KELA, (e)'
PKIRKKO = 'Puoliso: Veronsaajien osuudet: Kirkko, (e)'
PELTTVAKLAIT = 'Puoliso: Veronsaajien osuudet: Eläke- ja työttömyysvakuutuslaitokset, (e)'
PVERONSYHT = 'Puoliso: Veronsaajien osuudet yhteensä, (e)'

BRUTTOTULOT = 'Puolisot yhteensä: Bruttotulot, (e)'
VEROTYHT = 'Puolisot yhteensä:  Verot, (e)'
VEROJENOSTUL = 'Puolisot yhteensä: Verojen osuus tuloista, (%)'
NETTULOT = 'Puolisot yhteensä: Nettotulot, (e)'

%END;

INF = 'Inflaatiokorjauksessa käytettävä kerroin';

/* Määritellään formaatilla haluttu desimaalierotin  */
/* ja näytettävien desimaalien lukumäärä */

%IF &EROTIN = 1 %THEN %DO;
	FORMAT _NUMERIC_ 1&DESIMAALIT..&DESIMAALIT;
	FORMAT INF MARGIVERO VOSUUSPTULO VEROJENOSUUS 8.5;
%END;

%IF &EROTIN = 2 %THEN %DO;
	FORMAT _NUMERIC_ NUMx1&DESIMAALIT..&DESIMAALIT;
	FORMAT INF MARGIVERO VOSUUSPTULO VEROJENOSUUS NUMx8.5;
%END;

/* Kokonaislukuina ne muuttujat, joissa ei haluta käyttää desimaalierotinta */
 
FORMAT 
/* Yleiset ja viitehenkilön muuttujat */
VERO_VUOSI VERO_VAKASU VERO_PUOLISO VERO_IKA VERO_LAPSIA VERO_EVLAPSIA VERO_OPISK VERO_YRIT VERO_TYOTKUUK
VERO_KIRKOSSA VERO_VAIHT VERO_OSPKORKO VERO_KUUKAUDET VERO_KESKIM VERO_INVOIKEUS82
/* Puolison muuttujat siinä tapauksessa että puoliso on */
%IF &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;
VERO_PVAKASU VERO_PIKA VERO_PEVLAPSIA VERO_POPISK VERO_PYRIT VERO_PTYOTKUUK
VERO_PKIRKOSSA VERO_PKUUKAUDET VERO_PKESKIM VERO_PINVOIKEUS82
%END;
8.;

KEEP &VALITUT ;

RUN;

* Tulosten printtaus ja vienti exceliin riippuen valinnasta; 
%EsimTulokset(&TULOSNIMI_VE, VERO);

%MEND Vero_Simuloi_MargVero;

%Vero_Simuloi_MargVero;
